### DISCUSSION TITLE
Blueprint for turning on a plug when Current Rate Electricity is below X

### DISCUSSION THREAD

**Discussion by xRDHS** [BottlecapDave/HomeAssistant-OctopusEnergy#1019] [Q&A] [answered]
I've been trying to run an automation for when Current Rate Electricity changes and is below a certain price, to turn on a tuya plug.

Nothing I'm trying is not working of triggering, is there an example for this or a blueprint?

**Comment by BottlecapDave** [comment]
Hello. You want to look at [numeric_state](https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger) triggers to account for this. Something like the following

```yaml
automation:
  triggers:
    - trigger: numeric_state
      entity_id: sensor.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}_{{MPAN_NUMBER}}_current_rate
      below: 0.10 # 10p
  actions:
   - action: switch.turn_on
     target:
        entity_id: switch.tuya_plug
```

Alternatively you could look at [target rate sensors](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/target_rate/) to turn on for more complicated scenarios, which can then be used with a [state trigger](https://www.home-assistant.io/docs/automation/trigger/#state-trigger).
