### DISCUSSION TITLE
Missing free electric event

### DISCUSSION THREAD

**Discussion by jasonwragg** [BottlecapDave/HomeAssistant-OctopusEnergy#1099] [General]
Predbat mentions the following event:

octopus_free_session: 're:(event.octopus_energy_([0-9a-z_]+|)_octoplus_free_electricity_session_events)'

But it doesn't seen to exist in my Octopus integration, in my meter device there is no event to enable.

Is this a thing or is it wrong in the Predbat documentation?

**Comment by BottlecapDave** [comment]
Hello. You need to have signed up to Octoplus. You also need to be on the latest version of the integration (v13.1.3). The entity is also not associated with any device because it's linked to your account. If you look at entities instead of devices within the integration, you should see the entity.

**Comment by mehtadone** [comment]
Hi, I'm facing the same issue. 

I am signed up to Octoplus, I have points etc and get the session emails. I am on version 16.2. 

If I look at entities, I see the sensor with the correct information, but no event which predbat seems to require. 

```
<html>
<body>
<!--StartFragment-->
sensor.octopus_energy_electricity_xxxx_xxxx_octoplus_free_electricity_session_baselineOctoplus Free Electricity Session Baseline Electricity (25J0238750/1012848791539) | 0.0 | state_class: total unit_of_measurement: kWh device_class: energy icon: mdi:lightning-bolt friendly_name: Octoplus Free Electricity Session Baseline Electricity (xxxx/xxxx) start: 2025-08-31T14:00:00+01:00 end: 2025-08-31T14:30:00+01:00 is_incomplete_calculation: true consumption_items:  - start: '2025-08-24T14:00:00+01:00'   end: '2025-08-24T14:30:00+01:00'   consumption: 0 - start: '2025-08-23T14:00:00+01:00'   end: '2025-08-23T14:30:00+01:00'   consumption: 0 - start: '2025-08-17T14:00:00+01:00'   end: '2025-08-17T14:30:00+01:00'   consumption: 0  total_baseline: 0 baselines:  - start: '2025-08-31T14:00:00+01:00'   end: '2025-08-31T14:30:00+01:00'   baseline: 0   is_incomplete_calculation: true - start: '2025-08-31T14:30:00+01:00'   end: '2025-08-31T15:00:00+01:00'   baseline: 0   is_incomplete_calculation: true
-- | -- | --

<!--EndFragment-->
</body>
</html>[sensor.octopus_energy_electricity_xxxx_xxxx_octoplus_free_electricity_session_baseline](http://homeassistant.local:8123/developer-tools/state#)
Octoplus Free Electricity Session Baseline Electricity (xxxx_xxxx)
0.0	state_class: total
unit_of_measurement: kWh
device_class: energy
icon: mdi:lightning-bolt
friendly_name: Octoplus Free Electricity Session Baseline Electricity (xxxx_xxxx)
start: 2025-08-31T14:00:00+01:00
end: 2025-08-31T14:30:00+01:00
is_incomplete_calculation: true
consumption_items: 
- start: '2025-08-24T14:00:00+01:00'
  end: '2025-08-24T14:30:00+01:00'
  consumption: 0
- start: '2025-08-23T14:00:00+01:00'
  end: '2025-08-23T14:30:00+01:00'
  consumption: 0
- start: '2025-08-17T14:00:00+01:00'
  end: '2025-08-17T14:30:00+01:00'
  consumption: 0

total_baseline: 0
baselines: 
- start: '2025-08-31T14:00:00+01:00'
  end: '2025-08-31T14:30:00+01:00'
  baseline: 0
  is_incomplete_calculation: true
- start: '2025-08-31T14:30:00+01:00'
  end: '2025-08-31T15:00:00+01:00'
  baseline: 0
  is_incomplete_calculation: true
```

I see this in my predbat logs: 

```
<html>
<body>
<!--StartFragment-->
2025-08-31 10:35:38.153734: Warn: Regular expression argument: octopus_free_session unable to match re:(event.octopus_energy_([0-9a-z_]+\|)_octoplus_free_electricity_session_events), now will disable
--
14910 | 2025-08-31 10:35:38.151080: Warn: Regular expression argument: octopus_ready_time unable to match re:(time.octopus_energy_([0-9a-z_]+\|)_intelligent_target_time), now will disable
14909 | 2025-08-31 10:35:38.147937: Warn: Regular expression argument: octopus_intelligent_slot unable to match re:(binary_sensor.octopus_intelligent_slot\|re:binary_sensor.octopus_energy_intelligent_dispatching), now will disable

<!--EndFragment-->
</body>
</html>
```

Help really appreciated.
