### DISCUSSION TITLE
Tariff Comparison Sensors - Tracker Gas

### DISCUSSION THREAD

**Discussion by townsmcp** [BottlecapDave/HomeAssistant-OctopusEnergy#1196] [Q&A] [answered]
Hi, I have been trying to follow the Tariff Comparison instructions https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/tariff_comparison/ but have fallen at the first hurdle - `Product Code`. I follow the API link and try to find the Gas Tracker product code but cant find it in the https://api.octopus.energy/v1/products/ link. Can someone point me in the right direction? Can tariff comparison sensor be setup for Tracker products?

**Comment by BottlecapDave** [comment]
Not sure why it's not appearing, but I think the product you're after is SILVER-24-12-31

**Reply by townsmcp** [reply]
Thank you @BottlecapDave. I will give that a go and see what happens. Just to confirm, this is the code for gas tracker? What I’m looking to do is create a sensor to compare the current gas fixed 14m (which I changed over to today) to the gas tracker December 2024 v1 (which I was going to be moving over to mid Feb when the December 2023 ran out)

**Reply by BottlecapDave** [reply]
This is the product. You can then use the API to look up the tariff code. This is one that people are moving over to in February to my knowledge (I am also tracking this)

**Comment by townsmcp** [comment, marked as answer]
Thanks @BottlecapDave for the help. Just in case anyone stumbles across this thread, here is how I am now tracking the daily tracker changes in HA - I intend to keep an eye on prices to eventually move back.

### Create a new helper for the product code
Type: input text
Name: Octopus Gas Product Code
Entity ID: input_text.octopus_energy_gas_product
Icon: phu:octopusenergy

I have Custom Band Icons installed for the Octopus icon

### Create a new rest sensor to grab the prices based on the helper
```
sensor:
  - platform: rest
    name: Octopus Energy Tracker Daily Gas Price
    unique_id: octopus_energy_gas_price_sensor
    icon: mdi:fire
    resource_template: >-
      https://api.octopus.energy/v1/products/{{ states('input_text.octopus_energy_gas_product') }}/gas-tariffs/G-1R-{{ states('input_text.octopus_energy_gas_product') }}-J/standard-unit-rates/
    method: GET
    headers:
      Accept: application/json
    value_template: "{{ value_json.results[0].value_inc_vat }}"
    unit_of_measurement: "p/kWh"
    scan_interval: 86400
```
My region is South East (area code J). Update the code as appropriate for your area by changing the value `-J/standard.....`

### Create an automation to update the sensor at a given time
```
alias: Update Octopus Energy Gas Price at 1 AM
description: Fetch the latest Octopus Energy Tracker Gas Price daily at 1 AM
triggers:
  - at: "01:00:00"
    trigger: time
conditions: []
actions:
  - target:
      entity_id: sensor.octopus_energy_daily_gas_price
    action: homeassistant.update_entity
    data:
      entity_id:
        - sensor.octopus_energy_daily_gas_price
mode: single
```

**Reply by BottlecapDave** [reply]
The tariff comparison will compare your costs against your real consumption which is what I use to plot on a graph to see which tariff my costs would be cheaper on. The tariff comparison also includes an additional sensor that has the rates available as an attribute. The rates and cost will be for the same day as the previous consumption sensor.

```yaml
chart_type: line
period: hour
type: statistics-graph
entities:
  - >-    sensor.octopus_energy_electricity_xxx_yyy_previous_accumulative_cost
  - >-  sensor.octopus_energy_electricity_xxx_yyy_previous_accumulative_cost_tariff_1
  - >-   sensor.octopus_energy_electricity_xxx_yyy_previous_accumulative_cost_next_tariff_2
stat_types:
  - state
```
