### DISCUSSION TITLE
Using Target Rate sensors

### DISCUSSION THREAD

**Discussion by yebaws** [BottlecapDave/HomeAssistant-OctopusEnergy#284] [General]
Please bear with me, I'm on a steep learning curve just now.

I want to charge my batteries during the cheapest 2 1/2 hours periods between 00:00 and 08:00

Have set up a target rate sensor to check for the 2 cheapest periods. It's working fine as I can see the entity with the correct times chosen in the attributes. I just don't know what syntax to use to put the start and end times into an automation to set my charge start and finish times. 

These are the attributes:

![attributes](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/136797733/60538244-29b8-4ca7-8dd2-c67ec90965dc)

**Comment by BottlecapDave** [comment]
Hi there. You just need your automation to look at your target rate sensor and look at the state. When the state is on, this will be the discovered cheap periods. This way you don't need to look at extracting the times.

**Comment by yebaws** [comment]
Thanks for the reply @BottlecapDave. I see now how I can set up an automation with a trigger when the state of my target rate sensor changes to "on". 

The problem is that I want my batteries to charge during the selected cheap periods by connecting to my LuxPower inverter and changing the charge settings there.

I don't have any way that I can just switch the charge "on" and "off", which would be ideal with this trigger. I need to set the start and end times for the charge. I guess maybe I could just set the start time to the current time (although I'm not sure how I do that?) so charging would start immediately and the end time to an hour later, then when the sensor state changes to "off" I can change the times to stop the charging. Guess it might work...

Do you know of a simpler way?

**Reply by BottlecapDave** [reply]
Because you're looking for intermediate times, this is going to be difficult with the current setup as there is currently no way of determining which rate block you're currently in. With the current setup you would need to set the start time to now and then the end time to now + `current_duration_in_hours`. I'm not sure what happens with your inverter if you set the start time to now or in the past if that will turn it on straight away. However If this works out for you, then you want something like

trigger:
```
platform: state
entity_id:
  - binary_sensor.octopus_energy_target_one_hour_intermittent_next_time_charge_between_midnight_and_eight
to: "on"
```

To get the end date, to pass to your inverter you can use the following template
```
{% set hours = state_attr('binary_sensor.octopus_energy_target_one_hour_intermittent_next_time_charge_between_midnight_and_eight', 'current_duration_in_hours') %} 
{{ now() + timedelta(hours=hours) }}
```

this will return a datetime. If you need it in a certain format you can use [templating overrides](https://www.home-assistant.io/docs/configuration/templating/) to alter the output. For instance if you want it in `HH:MM` format you would have.

```
{% set hours = state_attr('binary_sensor.octopus_energy_target_one_hour_intermittent_next_time_charge_between_midnight_and_eight', 'current_duration_in_hours') %} 
{{ (now() + timedelta(hours=hours)).strftime("%H:%M") }}
```

I'll have a look at exposing the upcoming rate information more easily in the future, but I can't give you an ETA at the moment.

**Reply by yebaws** [reply]
Thanks for the reply. This should be worth a go. I'm now wondering though if I might be able to do it another way. There is a disable / enable charge option which I can control through HA integration. So I could set the charge times to 00:00 - 23:59, disable charging by default and then use the trigger to toggle this switch.

**Reply by BottlecapDave** [reply]
Yeah that sounds like the simplist way to go. I was also having a moment with my previous response as you could have you automation update the times every time the sensor turns off.

trigger:
```
platform: state
entity_id:
  - binary_sensor.octopus_energy_target_one_hour_intermittent_next_time_charge_between_midnight_and_eight
to: "off"
```

and then your service would use a template to find the start time

```
{{ (state_attr('binary_sensor.octopus_energy_target_one_hour_intermittent_next_time_charge_between_midnight_and_eight', 'next_time').strftime("%H:%M") }}
```

and end time

```
{% set hours = state_attr('binary_sensor.octopus_energy_target_one_hour_intermittent_next_time_charge_between_midnight_and_eight', 'next_duration_in_hours') %} 
{{ (state_attr('binary_sensor.octopus_energy_target_one_hour_intermittent_next_time_charge_between_midnight_and_eight', 'next_time') + timedelta(hours=hours)).strftime("%H:%M") }}
```

**Comment by yebaws** [comment]
OK, this is what I've come up with. To start charge:

```
platform: state
entity_id:
  - >-
    binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
attribute: next_min_cost

condition: state
entity_id: >-
  binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "on"

service: switch.turn_on
data: {}
target:
  entity_id: switch.lux_ac_charge_enable
```
And the to stop charge:

```
platform: state
entity_id:
  - >-
    binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
attribute: next_min_cost

condition: state
entity_id: >-
  binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "off"

service: switch.turn_off
data: {}
target:
  entity_id: switch.lux_ac_charge_enable
```

The actions work fine as I can test them by running that part of the automation. Not sure how / if I can test the triggers or conditions. Does it look like they will do the job? Reluctant to test tonight as there is some serious plunge pricing that I don't want to miss!

**Reply by BottlecapDave** [reply]
Based on your conditions, you can move the condition to be your trigger as you have a service to turn the batteries on/off so it looks like

```
platform: state
entity_id:
  - >-
    binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "on"

service: switch.turn_on
data: {}
target:
  entity_id: switch.lux_ac_charge_enable
```

```
platform: state
entity_id:
  - >-
    binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "off"

service: switch.turn_off
data: {}
target:
  entity_id: switch.lux_ac_charge_enable
```

You could also update your automation to take advantage of plunge prices by having it as an additional trigger

```
- platform: state
entity_id:
  - >-
    binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "on"
- platform: numeric_state
entity_id:
  - >-
    binary_sensor.octopus_energy_xxx_xxx_current_rate
below: 1

service: switch.turn_on
data: {}
target:
  entity_id: switch.lux_ac_charge_enable
```

```
- platform: state
entity_id:
  - >-
    binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "off"
- platform: numeric_state
entity_id:
  - >-
    binary_sensor.octopus_energy_xxx_xxx_current_rate
above: 0

condition: state
entity_id: >-
  binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "off"

service: switch.turn_off
data: {}
target:
  entity_id: switch.lux_ac_charge_enable
```

The latter automation includes a condition to account for the target rate including some plunge prices (e.g. you want 1 hour but there's only 30 min plunge) so that when it goes back up it doesn't turn off your batteries and give you a short charge

But really, there are so many ways of building automations, I wouldn't say there's any wrong way. As long as it does what you want It's whatever works for you and sometimes this comes down to readability for yourself :)

**Reply by yebaws** [reply]
@BottlecapDave excellent, thank you for all your help

**Reply by yebaws** [reply]
@BottlecapDave when I try your code, code editor returns "Message malformed: extra keys not allowed @ data['platform']" and won't let me save the code. Not sure what is causing this?

**Reply by BottlecapDave** [reply]
Sorry I should have been clearer. The second platform statement is a separate trigger and so needs to be copied separately.

**Comment by yebaws** [comment]
No, I was just using this:

```
platform: state
entity_id:
  - >-
    binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
state: "on"

service: switch.turn_on
data: {}
target:
  entity_id: switch.lux_ac_charge_enable`
```

...when I was getting the error

**Reply by BottlecapDave** [reply]
I was basing it on your example, but you're right that it's not a fully formed automation. I wasn't sure how you'd be importing it back in. If importing the yaml, you're looking at

```yaml
alias: turn on batteries
description: ""
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
    to: "on"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.lux_ac_charge_enable
```

```yaml
alias: turn off batteries
description: ""
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
    to: "off"
action:
  - service: switch.turn_off
    target:
      entity_id: switch.lux_ac_charge_enable
```

```yaml
alias: turn on batteries
description: ""
mode: single
trigger:
  - platform: state
    entity_id: >-
      binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
    to: "on"
  - platform: numeric_state
    entity_id: binary_sensor.octopus_energy_xxx_xxx_current_rate
    below: 1
action:
  - service: switch.turn_on
    target:
      entity_id: switch.lux_ac_charge_enable
```

```yaml
alias: turn off batteries
description: ""
mode: single
trigger:
  - platform: state
    entity_id: >-
      binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
    to: "off"
  - platform: numeric_state
    entity_id: binary_sensor.octopus_energy_xxx_xxx_current_rate
    above: 0
condition:
  - condition: state
    entity_id: >-
      binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
    state: "off"
action:
  - service: switch.turn_off
    target:
      entity_id: switch.lux_ac_charge_enable
```

**Comment by yebaws** [comment]
Still get the same error with that code. 

```
alias: turn on batteries
description: ""
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight
    state: "on"
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.lux_ac_charge_enable
```

Do you not get that error with visual editor? For me, I can only get it to be accepted by the editor if I also use "condition" as per my original snippets. The code is just a little bit longer and I *think* it will do what I want. Will test it tonight.

**Reply by BottlecapDave** [reply]
I've updated the above examples. You import the examples from the three dots at the top right of the screen (the whole automation) rather than the individual sections.

**Comment by yebaws** [comment]
Thanks, that is accepted and what comes up in the visual editor after saving the code makes sense also. 

Running the "on" automation to test toggles the charge enable switch to "on" and running the off automation toggles it to off. 

I wouldn't have expected running the on automation to change the charge enable to "on" as the conditions for the trigger (cheapest 2 half hour slots between 00:00 and 08:00) are not currently met, but I guess that using "run" to test the automation maybe just runs the actions, regardless of whether the triggers are met? 

Is there a way to display the state of the entity "binary_sensor.octopus_energy_target_one_hour_intermittent_night_time_charge_between_midnight_and_eight" to check if it is currently on or off?

**Reply by BottlecapDave** [reply]
You're correct in saying running automations does indeed skip the triggers. If you have any conditions they should be adhered too.

In terms of displaying if the sensor is turned on/off you can add the entity to your dashboard using the entity card, or look in your developer options.

**Comment by yebaws** [comment]
@BottlecapDave automation ran smoothly last night, now I can start making things more complicated! Thanks again for your help.

**Comment by yebaws** [comment]
This is slightly off topic but the in the same area...

What I want to do is turn on certain appliances when there is plunge pricing:

```
alias: Plunge pricing turn on high loads
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.octopus_energy_electricity_xxxx_xxxx_current_rate
    below: 0
action:
  - service: switch.turn_on
    target:
      device_id:
        - e57a05ea1bde2df7539a8a02344c044e
        - 4778d134938e4987a17ad92e62c45429
        - 7195e0682d82a452fbbac3da66def715
    data: {}
mode: single
```

This does the job. But the issue is that these appliances will stay on when the rates become positive again. I could write another automation that was basically the same, substituting "below" for "above" and "on" for "off". This would then turn them off when the prices became positive. But it would mean that they would basically always be turned off when prices were above 0 and this automation would over-ride others trying to turn the appliances on.

So I want an automation that will only switch off the devices when the rate changes from negative to positive - not just whenever it is positive. I've had a few goes with repeat statements with no luck. What is the correct code / routine?

A target sensor that just detected when prices were below 0 would work perfectly as that could toggle the switch, but you always seem to have to put intervals / times into the target rate sensors.


So I want an automation that will only switch off the devices when the rate changes from negative to positive - not just whenever it is positive. I've had a few goes with repeat statements with no luck. What is the correct code / routine?
