### DISCUSSION TITLE
A card to show current months cost?

### DISCUSSION THREAD

**Discussion by realtek2017** [BottlecapDave/HomeAssistant-OctopusEnergy#296] [General]
Is it possible to show a card which shows the cost for the current month/billing period?

**Comment by BottlecapDave** [comment]
Hi. I didn't want to waste development time adding functionality that can be achieved in other ways with HA. Everyone also has different requirements that would balloon the number of sensors. I have it on my list to provide examples, but to achieve what you want you can use the [utility meter](https://www.home-assistant.io/integrations/utility_meter/). For cost you will want the following

```yaml
monthly_electricity_cost:
  source: sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_cost
  name: Monthly Electricity Cost
  cycle: monthly
  delta_values: true
  offset:
    # Because we're a day behind with the costs, we need an offset of 1 day
    days: 1
```

You can then add this to your dashboard for viewing. I have it on my list to have a sensor for current cost (if you have a Home Mini) which would give you a sensor which would update more frequently.

**Comment by badguy99** [comment]
I had this set up, basically as above (different offset day due to when my billing is). However, since v9.0.0 the cost seem to increase every 30 minutes, rather than daily, which is ballooning the reported monthly cost. I'm currently running v9.0.2 and still see the issue.

**Reply by BottlecapDave** [reply]
It looks like the utility sensor is not ignoring changes to just attributes. I'll have a look when I get a chance

**Comment by BottlecapDave** [comment]
Hello. Sorry for not responding sooner, but I was waiting for December to trick over and reset the utility meter and then forgot.

You'll need to update the utility meter (or create a new one) with the following configuration

```
monthly_electricity_cost:
  source: sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_cost
  name: Monthly Electricity Cost
  cycle: monthly
  offset:
    # At least one of these must be specified:
    days: 1
```

The key part is you need to target the accumulative sensors and therefore not have `delta` enabled.

Unfortunately with some new attributes added to the non accumulative sensor and no way of only focusing on state changes (like automations), it's not suited for utility meters.
