### DISCUSSION TITLE
target rate sensors "end_time" is ambiguous when you have 2d of rate data

### DISCUSSION THREAD

**Discussion by BobC76** [BottlecapDave/HomeAssistant-OctopusEnergy#326] [Q&A] [answered]
Hi, great plug in and thanks for the hard work supporting this.

I've set up a target rate sensor which I refresh automatically when Octopus Agile rates for the next day come out. However, if I set start_time to say 16:00 (roughly when the new rate data is published) then end_time to 23:00 its ambiguous whether that means today, or tomorrow. I want it to mean tomorrow, but seems like the sensor assumes today. Am I missing something?

Thanks

**Comment by BottlecapDave** [comment, marked as answer]
Hi there and glad you're finding the plugin useful.

As per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_target_rate.md#examples), the target rate sensor will always look for the best time for the most recent chosen period, in your case today between 16:00 and 23:00. This will be re-evaluated if new rates become available. Once the chosen period of time has passed, it will then look up the next time for the following period, in your case between 16:00 and 23:00 the following day. If you look up the attributes of the sensor (see example below), then it will show the periods that have been picked and the date/time the sensor will next come on.

<img width="398" alt="Screenshot 2023-07-25 210730" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/14993950/cf239fb6-9c59-4d90-9b43-7334e4c38c48">

**Reply by BobC76** [reply]
Ok thanks that's what I'd understood. So later today, when Octopus have published their rates from 26th through to 23:00 on 27th, if I set the range 16:00 - 16:00, I would get a 24h period from 16:00 on 26th to 16:00 on 27th? 

I guess that will be sufficient as in most circumstances the best time to charge isn't going to be 16:00-23:00 anyway. 

I guess I'm wondering if there could be an option/enhancement to search all rates available up to the last rate returned by Octopus (i.e. 16:00 on 26th to 23:00 on 27th)?

**Reply by BobC76** [reply]
Update: discovered range 16:00 - 16:00 fails, has to be 16:00 to 15:59

The docs say 

> " If you're wanting to "shift" the evaluation period to be in line with something (e.g. agile pricing), you could set your from and to to something like 16:00"

 - but in my experiments that seemed to fail the sensor calculation and end needs to be (>1s?) before start?

**Reply by BottlecapDave** [reply]
> Update: discovered range 16:00 - 16:00 fails, has to be 16:00 to 15:59

That is odd, as I have my sensors set from 16:00 to 16:00 in my testing and it's working fine. The target rate sensor only evaluates when it has all rate data available for the requested period of time. So when you had it set from midnight to midnight, it wasn't evaluating until the next set of rates became available, which might have then decided the best period was in the past or for an hour in the future. So potentially you were missing some data for some reason. I'm planning in the future to make this more clear on the sensor and potentially have an option in the future to ignore full rate datasets being available on the understanding that the sensor may come on more than the desired time.

> I guess I'm wondering if there could be an option/enhancement to search all rates available up to the last rate returned by Octopus (i.e. 16:00 on 26th to 23:00 on 27th)?

I won't be adding any feature to look beyond a maximum of a 24 hour period. This is because this is used to determine if the cheapest times are in the future, present or past to avoid the sensor from coming on more than requested. Other tariffs also provide rates that exceed 48 hours (because they're fixed). The data is available, so you're welcome to try and come up with your own automations to meet your needs.

**Reply by BobC76** [reply]
> That is odd, as I have my sensors set from 16:00 to 16:00 in my testing and it's working fine. The target rate sensor only evaluates when it has all rate data available for the requested period of time.

Hmm, maybe I was mistaken I'll keep an eye out later when the next set of 'tomorrow' rates come out. Anyway now I understand it better and I'm getting useful results :)

>I won't be adding any feature to look beyond a maximum of a 24 hour period. 

I agree no point looking ahead for fixed tariffs. I wasn't asking that it look further than the available Agile rates at the time. So that, assuming Octopus Agile rates for the day ahead are published at 4pm on 2nd Aug, the service could look right through to the last value available, 11pm on 3rd Aug. 

I guess the behaviour I was wondering about could be that if you leave end_time blank it could default to `rates[-1].valid_to` instead of `start_time + 1 day`, but might be trickier than I think not to break existing implementations. Just an idea, its a minor thing. I'd have a go at the code but not yet set up to build and test ;)

**Comment by BobC76** [comment]
Starting a separate thread on the start-end time possible issue.

Here's what I see this evening for my target rate sensor, which I just updated via the service octopus_energy.update_target_config:

```
Name: incoming_continuous
Hours: 2.5
Type: Continuous
MPAN: [MPAN]
rolling_target: false
last_rates: false
Start time: 20:12
End time: 20:12
offset: 00:00:00
is_target_export: false
target_times: 
overall_average_cost: 0p
overall_min_cost: null
overall_max_cost: null
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: null
next_duration_in_hours: 0
next_average_cost: null
next_min_cost: null
next_max_cost: null
icon: mdi:camera-timer
friendly_name: Octopus Energy Target incoming_continuous
```


```
2023-08-02 20:14:12.198 DEBUG (MainThread) [custom_components.octopus_energy.target_rates.target_rate] Updating OctopusEnergyTargetRate incoming_continuous
2023-08-02 20:14:12.198 DEBUG (MainThread) [custom_components.octopus_energy.target_rates.target_rate] Retrieving rates for '[MPAN]'
2023-08-02 20:14:12.198 DEBUG (MainThread) [custom_components.octopus_energy.target_rates.target_rate] 94 rate periods found
2023-08-02 20:14:12.199 DEBUG (MainThread) [custom_components.octopus_energy.target_rates] 2023-08-02 19:12:00+00:00 is after 2023-08-02 19:12:00+00:00, so setting target end to tomorrow
2023-08-02 20:14:12.199 DEBUG (MainThread) [custom_components.octopus_energy.target_rates] Finding rates between 2023-08-02 19:12:00+00:00 and 2023-08-03 19:12:00+00:00
2023-08-02 20:14:12.199 DEBUG (MainThread) [custom_components.octopus_energy.target_rates] Incorrect number of periods discovered. Require 48, but only have 47

```

If I set "End Time" to 20:11, I get 

```
Name: incoming_continuous
Hours: 2.5
Type: Continuous
MPAN: [MPAN]
rolling_target: false
last_rates: false
Start time: 20:12
End time: 20:11
offset: 00:00:00
is_target_export: false
target_times: 
- value_inc_vat: 2.898
  valid_from: '2023-08-03T01:30:00+00:00'
  valid_to: '2023-08-03T02:00:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-L
  is_capped: false
- value_inc_vat: 1.932
  valid_from: '2023-08-03T02:00:00+00:00'
  valid_to: '2023-08-03T02:30:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-L
  is_capped: false
- value_inc_vat: 1.449
  valid_from: '2023-08-03T02:30:00+00:00'
  valid_to: '2023-08-03T03:00:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-L
  is_capped: false
- value_inc_vat: 4.4835
  valid_from: '2023-08-03T03:00:00+00:00'
  valid_to: '2023-08-03T03:30:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-L
  is_capped: false
- value_inc_vat: 3.864
  valid_from: '2023-08-03T03:30:00+00:00'
  valid_to: '2023-08-03T04:00:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-L
  is_capped: false

overall_average_cost: 2.9253p
overall_min_cost: 1.449p
overall_max_cost: 4.4835p
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: 2023-08-03T01:30:00+00:00
next_duration_in_hours: 2.5
next_average_cost: 2.9253p
next_min_cost: 1.449p
next_max_cost: 4.4835p
icon: mdi:camera-timer
friendly_name: Octopus Energy Target incoming_continuous
```
I'm not sure what significance the log message "Incorrect number of periods discovered. Require 48, but only have 47" may have but clearly something is up if setting start and end to the same time should work?
