### DISCUSSION TITLE
Is there an entity that provides future rates?

### DISCUSSION THREAD

**Discussion by adamratson** [BottlecapDave/HomeAssistant-OctopusEnergy#410] [Q&A] [answered]
I'm looking to have a chart of the rates coming up in the day but can't see an entity for future rates - I know they're on the current rates card as an subset of the all rates attribute but couldn't see them in a standalone entity.
Cheers!

**Comment by BottlecapDave** [comment, marked as answer]
Currently the rates are not split up, The `all_rates` attribute of the sensor always includes the previous day, the current day and the next day's worth of rates in 30 minute increments. Therefore you could take the value of this attribute and start from index 96 to get tomorrows rates. I'm currently looking at better ways of exposing this information, but haven't found the time to investigate.

**Reply by adamratson** [reply]
Ah, okay cool - would it be okay for me to look at adding that as an entity? It would be useful for me to allow me to graph the upcoming rates

**Reply by BottlecapDave** [reply]
I've beat you to it, and currently have a branch where yesterday, today's and tomorrows rates are split into separate entities along with raising events everytime they refresh.

It's a work in progress but available on branch `feat/rate-events`.

**Reply by adamratson** [reply]
Oh, awesome! Cheers! Excited to see it when the release comes out!

**Comment by realflash** [comment]
Is this not https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/sensors/electricity.md#next-day-rates and its compatriots?

**Comment by adamratson** [comment]
I ended up creating the chart I wanted with ApexCharts!

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/10365463/3032aad7-8765-4ec7-bf2b-1096fc5c3af7)

If anyone wants to replicate :)

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 1d
span:
  start: hour
yaxis:
  - max: ~45
    min: ~0
header:
  show: true
  title: Upcoming rates
series:
  - entity: sensor.electricity_XXXXXXXXXX_XXXXXXXXXXXX_current_rate
    data_generator: >
      return entity.attributes.all_rates.map(r => [new
      Date(r.valid_from).getTime(), r.value_inc_vat]);
    color_threshold:
      - value: 0
        color: '#51c7e8'
      - value: 10
        color: '#2cc718'
      - value: 30
        color: '#db9c14'
      - value: 40
        color: '#b00020'
```
