### DISCUSSION TITLE
API question.

### DISCUSSION THREAD

**Discussion by andyblac** [BottlecapDave/HomeAssistant-OctopusEnergy#425] [Q&A]
Is there anything in the API that shows the status of the Home Mini?

Just i keep seeing that my Home Mini LED is RED, and wondered if there is anything in the API that shows the status (Online, No Internet,  API error etc), or the reason why it has gone RED.

**Comment by BottlecapDave** [comment]
Nothing to my knowledge I'm afraid. According to the [user guide](https://octopus.energy/octopus-home-mini-faq/#ohmguide), red means it's lost wifi connection

**Comment by andyblac** [comment]
could you add some logging as to when the Mini has gone offline ?

**Reply by BottlecapDave** [reply]
There is nothing in the APIs that can detail this. You could possibly build an automation around the `last_changed` value of the current demand sensor so that you get notified if the minutes exceed a threshold

```yaml
automation:
  trigger:
    - platform: template
      value_template: "{{ ((now() - states.sensor.octopus_energy_electricity_xxx_xxx_current_consumption.last_changed).seconds // 60) > 5 }}"
  action:
  // Do something
```
