### DISCUSSION TITLE
Need help with Template Sensors

### DISCUSSION THREAD

**Discussion by andyblac** [BottlecapDave/HomeAssistant-OctopusEnergy#427] [General]
I would like to setup some template sensors for Weekly, Monthly and Yearly for both GAS and Electric any idea how I can get the sensors state to reset each week, month, year ?

Thanks.

**Comment by BottlecapDave** [comment]
Hello. You're probably after [utility_meter](https://www.home-assistant.io/integrations/utility_meter/). I believe you could set it up to be like the following

```yaml
monthly_electricity_consumption:
  source: sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_consumption
  name: Monthly Electricity Cost
  cycle: monthly
  offset:
    days: 1
```
