### DISCUSSION TITLE
Plunge Rates Sensor

### DISCUSSION THREAD

**Discussion by deepanshu-shukla** [BottlecapDave/HomeAssistant-OctopusEnergy#479] [Ideas]
Is there any option to have a plunge rate sensor that would turn on whenever the rates are negative?

**Comment by BottlecapDave** [comment]
If you're referring to powerups https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/375, which are only available in parts of the country, then the information isn't available via the API.

If you are referring to an agile tariff, then you can create a template sensor that looks at the current rate sensor.

**Reply by deepanshu-shukla** [reply]
Yes I meant agile rates and a sensor that turns on when the rates are negative ! I will check what you said about creating a template sensor based on current rate

**Comment by deepanshu-sh** [comment]
Thanks ! it worked.. now i am configuring my devices to use this sensor !

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/137650023/0680319c-a6fe-47ae-b4b0-90e68d2455a4)

**Reply by anothermort** [reply]
Can you share how you got this to work?
As a bit of a newbie with HA.

Thanks

**Comment by deepanshu-sh** [comment]
it's actually very simple, just add the below in configuration.yaml and then change the name icon etc from UI

```
template:
  - binary_sensor:
      name: octopus_agile_plunge_target
      unique_id: x68_a0t_7t1
      state: "{{ (states('sensor.octopus_energy_electricity_xxxx_yyyy_current_rate') | float(0)) <  0.0 }}"
```
