### DISCUSSION TITLE
Apex charts not working with previous days consumption

### DISCUSSION THREAD

**Discussion by wymes** [BottlecapDave/HomeAssistant-OctopusEnergy#584] [General]
Hi 

before the recent changes  I could produce an apex chart  that showed the electricity consumption in a bar  char for the previous day . Using the new entity  I can no no longer display the half hourly  data even though the attribute data is there  . The chart data appears to recognise the first  period of the day but does not  produce a bar.

the chart is based on the following discussion
https://community.home-assistant.io/t/octopus-energy-integration-display-graph-of-usage/484018

```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Electricity Consumption KWH
  show_states: true
  colorize_states: true
show:
  last_updated: true
graph_span: 24h
span:
  start: day
  offset: '-1d'
series:
  - entity: >-
      sensor.octopus_energy_electricity_my-ser-no._my-mpan_previous_accumulative_consumption
    data_generator: |
      return entity.attributes.charges.map((reading) => {
        return [new Date(reading.from).getTime(), reading.consumption];
      });
    type: column
    color: Purple
```

Regards

NS
