### DISCUSSION TITLE
Saving Session example template error

### DISCUSSION THREAD

**Discussion by borpin** [BottlecapDave/HomeAssistant-OctopusEnergy#588] [General]
Firstly this is just a brilliant integration.

I'm trying to use this example https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/main/_docs/services.md#automation-example-1 to Join a saving event automatically.

It doesn't work and I wonder if the events and structure of the attributes has changed, or the entity is not persistent. I am on the latest version of the integration.

First issue is the Automation YAML is not properly formatted/structured. When I correct that, HA complains about the event data.

Looking at the events available, all I have in the Events is `octopus_energy_all_octoplus_saving_sessions` and in the States,  `event.octopus_energy_a_xxxxxxx_octoplus_saving_session_events` which has an array (empty as I've already joined) of `available_events`. Should this be the array that is accessed?

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/1322749/a732b1bf-7c02-4627-9c56-4ae7a2c3b59f)

However, I could be completely wrong as I don't really understand events (yet).

**Comment by BottlecapDave** [comment]
Hello.

The event that is highlighted on that entity is the one that the entity listens for, but does not contain all events. The event highlighted on the example is only fired when retrieving saving sessions and there's a session that hasn't been seen before in the available events array. When events are triggers, you can't "test" the automation because the event trigger data will be empty. If you join the session outside of HA before HA has a chance to update the data then the event will never fire as it will go straight into the joined events array.

As for the automation itself, it's based on one I use that is configured via yaml rather than through the UI. Ive just merged a PR from another user that updates these to be more UI friendly so they can be pasted in. Below is mine, which is a variation of what's in the docs and triggered yesterday. Notify channels event is my own custom event.

```
alias: OE - Join Saving Session
trigger:
  - platform: event
    event_type: octopus_energy_new_octoplus_saving_session
condition: []
action:
  - service: octopus_energy.join_octoplus_saving_session_event
    data:
      event_code: |
        {{ trigger.event.data["event_code"] }}
    target:
      entity_id: event.octopus_energy_xxx_octoplus_saving_session_events
  - event: notify_channels
    event_data_template:
      mode: message
      title: Saving Session
      message: >
        Joined new Octopus Energy saving session. It starts at {{
        trigger.event.data["event_start"].strftime('%H:%M') }} on {{
        trigger.event.data["event_start"].day }}/{{
        trigger.event.data["event_start"].month }} 
      length_hint: "00:00:07"
```

**Reply by borpin** [reply]
Using that code (with my account of course), I get the following error when trying to save it.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/1322749/6e14fbff-781d-4b03-bd2c-1e8a7f4b5d62)

**Reply by borpin** [reply]
There is an active event now, but I am still seeing this error when trying to create an Automation.

In the States tab, I can see the attribute data for `event.octopus_energy_xxxx_octoplus_saving_session_events`

```
event_types:
  - octopus_energy_all_octoplus_saving_sessions
event_type: octopus_energy_all_octoplus_saving_sessions
account_id: xxxx
available_events:
  - id: 1166
    code: EVENT_3_011223
    start: "2023-12-01T16:30:00+00:00"
    end: "2023-12-01T18:00:00+00:00"
    octopoints_per_kwh: 3200
joined_events:
  - id: 1165
    start: "2023-11-29T17:00:00+00:00"
    end: "2023-11-29T18:30:00+00:00"
    rewarded_octopoints: null
    octopoints_per_kwh: 3200
friendly_name: Octopus Energy xxxx Octoplus Saving Session Events
```

I can see the event in the Events tab
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/1322749/f2c078fa-86e6-4b0f-ad1c-c233617e101a)

Is there data associated with this event? If so how can I see the data, it isn't listed in the States tab.

**Reply by BottlecapDave** [reply]
Events just exist and the only way to see their data is either via event entities or by listening for the event via the developer tools.

I assume you've updated the failing step in the automation to point at your entity as the target?

**Reply by borpin** [reply]
> I assume you've updated the failing step in the automation to point at your entity as the target?

Not sure what you mean by this and perhaps that is what I am not doing.

**Reply by BottlecapDave** [reply]
The automation example in the docs is as follows

```
alias: Octopus Saving Session joiner
description: Automatically join Octopus Saving Session Events
mode: single
trigger:
  - platform: event
    event_type: octopus_energy_new_octoplus_saving_session
condition: []
action:
  - service: octopus_energy.join_octoplus_saving_session_event
    data:
      event_code: '{{ trigger.event.data["event_code"] }}'
    target:
      entity_id: event.octopus_energy_{{ACCOUNT_ID}}_octoplus_saving_session_events
  - service: persistent_notification.create
    data:
      title: "Octopus Saving Sessions Updated"
      message: >
        Joined new Octopus Energy saving session. It starts at {{ trigger.event.data["event_start"].strftime('%H:%M') }} on {{ trigger.event.data["event_start"].day }}/{{ trigger.event.data["event_start"].month }} 
```

When adding it, you'll need to replace `event.octopus_energy_{{ACCOUNT_ID}}_octoplus_saving_session_events` with the name of the entity in your setup. It will be something like `event.octopus_energy_a_xxx_octoplus_saving_session_events`
