### DISCUSSION TITLE
Long Term Statistics

### DISCUSSION THREAD

**Discussion by andyblac** [BottlecapDave/HomeAssistant-OctopusEnergy#642] [General]
@BottlecapDave do you have any ideas why `sensor.octopus_energy_gas_xxxxx_xxxxxx_current_consumption`, would not show in the new History dashboard for LTS?, it does have the data according to Statistics in dev view

<img width="520" alt="Screenshot 2023-12-18 at 13 03 32" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/77936/b3e6b20b-79a6-4de4-a869-332d615207d3">

but it not showing...
<img width="1555" alt="Screenshot 2023-12-18 at 13 02 44" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/77936/ff4efd19-b936-4831-9644-0535b28fd903">

it is also the same with Electric.

The `sensor.octopus_energy_gas_xxxxxx_xxxxxx_current_accumulative_consumption` seems fine.
<img width="1555" alt="Screenshot 2023-12-18 at 13 13 46" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/77936/df509e27-0d71-4f63-a6cc-7521cd9a6cba">

**Comment by andyblac** [comment]
```yaml
state_class: total
last_reset: "2023-12-18T13:53:04.226073+00:00"
unit_of_measurement: kWh
device_class: energy
icon: mdi:fire
friendly_name: Gas Current Consumption
last_evaluated: "2023-12-18T13:53:04.226073+00:00"
```
I see your using `state_class: total` for the sensor, should it not be `state_class: measurement` ??

> Measurement: The state represents a measurement in present time, not a historical aggregation such as statistics or a prediction of the future. Examples of what should be classified measurement are: current temperature, humidity or electric power.

> Total:  This state class should not be used for sensors where the absolute value is interesting instead of the accumulated growth or decline....

<img width="986" alt="Screenshot 2023-12-18 at 13 45 13" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/77936/d44c96c5-3546-4595-890c-e67f6287bc5c">
