### DISCUSSION TITLE
Gas Price, change from Pounds to pence

### DISCUSSION THREAD

**Discussion by liquidv** [BottlecapDave/HomeAssistant-OctopusEnergy#681] [General]
Might be a silly question and not sure if already asked, but how do you change the Gas Tracker Price from Pounds to Pence?
Instead of it displaying as 0.046 GBP/kWh, is it possible to display it to 4.6p / kWh?

![gas price](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/122752718/2c20163d-37b3-41b3-a646-b78918fd0f78)

**Comment by pcb1962** [comment]
You can create yourself a template sensor
(This is the old format, I haven't got around to converting these yet)

```
- platform: template
  sensors:
    octopus_gas_current_rate:
      unique_id: "oct_gas_current_rate"
      friendly_name: "gas current rate"
      value_template: "{{ (states('sensor.octopus_energy_gas_xxxxxx_xxxxxxx_current_rate') | float(0) * 100) | round(2) }}"
      unit_of_measurement: "p"
      icon_template: "mdi:currency-gbp"
```
