### DISCUSSION TITLE
Tesla Powerwall and Octopus Saving Sessions

### DISCUSSION THREAD

**Discussion by Automatic-Bob** [BottlecapDave/HomeAssistant-OctopusEnergy#742] [Ideas]
Hi! Dave,
I am looking for an automation to tell the Tesla Powerwalls to export when the Octopus saving sessions start and to stop exporting when the Saving Session Stops. Is this something you can help with or do you know someone that can help with this?

**Comment by BottlecapDave** [comment]
I'm not familiar with how you integrate the tesla powerwalls in HA unfortunately. You might be better off asking in the HA forums.

**Comment by Automatic-Bob** [comment]
Hi! Dave,

Thank you for your replies.

Regards
Bob.

**Reply by BottlecapDave** [reply]
No problem. If you find out how to control the powerwall (e.g service or entity) and you still need assistance I'll be happy to help where I can

**Comment by Automatic-Bob** [comment]
Thanks Dave,

**Comment by gedger** [comment]
Bob,

If you haven't solved this yet then I'm happy to share my automations to do this?

Richard

**Comment by Automatic-Bob** [comment]
Hi! Richard,

I would be grateful if you will share your automation as I have not managed to solve this yet.

Regards
Bob.

**Reply by gedger** [reply]
Firstly it is not a straightforward process as it requires several components to work together. If you were hoping for a single automation as a complete solution then I haven't found one. You also need to be aware that Tesla is in the process of changing how all the API's (both official and unofficial) so things may stop working at any time! The Octopus tariff you are on also plays a part, I'm on Flux. Finally it is a great advantage to have Export to Grid enabled on your Powerwall as by default they don't have this enabled so I would recommend requesting this if you haven't already done so.

The basic principle is that the PW has to know that during the Powersave slot you must not use any grid electricity and you get paid a lot to export. This is done by changing the PW tariff via the App, there is an Python library which will do this (TeslaPy) but I haven't yet had time to integrate it...On Flux there is a slot that runs from 16:00 - 19:00 where both the import and export  rate is at the highest value so I never use any power during that period, this means I can't save any more during a Powersave event. However, I can export and get the same price as reducing import so at the start of the Powersave event my Automation enables the PW to export and stops at the end point. The PW can export at 5kWh maximum so for an hour Powersave event the maximum you can get is 5 x the published rate.

If you are on another tariff then you will have to manually change the tariff before and after each Powersave event to get the desired behaviour. This may or may not work for you?

If this is still of interest I'll post the next steps?

**Comment by Automatic-Bob** [comment]
Hi! Richard,
Yes, I am still interested as I have 3x powerwall that allow me to export 15kwh and I am on octopus intelligent go tariff.
Regards
Bob.

Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Reply by gedger** [reply]
So you'll need to install the Tesla Custom Integration via HACS, this gives control of PW.

Then there are two automations. The first auto signs up to the event and sets some time/date helpers which are used to trigger the second automation. The second automation triggers on the time/date helpers set above and does the export. You will have to change the XX to match your account number.

```
alias: Energy - Octopus Power Save Auto SignUp
description: ""
trigger:
  - platform: state
    entity_id:
      - event.octopus_energy_a_XX_octoplus_saving_session_events
    attribute: available_events
condition:
  - condition: template
    value_template: >-
      {{
      state_attr('event.octopus_energy_a_XX_octoplus_saving_session_events',
      'available_events') | length > 0 }}
action:
  - variables:
      event_id: >-
        {{
        state_attr('event.octopus_energy_a_XX_octoplus_saving_session_events',
        'available_events')[0]['id'] }}
      event_code: >-
        {{
        state_attr('event.octopus_energy_a_XX_octoplus_saving_session_events',
        'available_events')[0]['code'] }}
      event_start: >-
        {{
        state_attr('event.octopus_energy_a_XX_octoplus_saving_session_events',
        'available_events')[0]['start'] }}
      event_end: >-
        {{
        state_attr('event.octopus_energy_a_XX_octoplus_saving_session_events',
        'available_events')[0]['end'] }}
      event_price: >-
        {{
        state_attr('event.octopus_energy_a_XX_octoplus_saving_session_events',
        'available_events')[0]['octopoints_per_kwh'] }}
  - service: octopus_energy.join_octoplus_saving_session_event
    data:
      event_code: |
        {{ event_code }}
    target:
      entity_id: event.octopus_energy_a_XX_octoplus_saving_session_events
  - service: input_datetime.set_datetime
    data:
      datetime: |
        {{ event_start }}
    target:
      entity_id: input_datetime.octopus_saving_start
  - service: input_datetime.set_datetime
    data:
      datetime: |
        {{ event_end }}
    target:
      entity_id: input_datetime.octopus_saving_end
  - service: input_number.set_value
    target:
      entity_id: input_number.octopus_saving_price
    data:
      value: |
        {{ event_price | float(1)/800.0 }}
  - service: notify.emailrich
    metadata: {}
    data:
      title: Octopus Power Save Event
      data:
        message: >-
          Octopus Power Save Event starting: {{ event_start }} ending: {{
          event_end }}
mode: single
```

**Reply by gedger** [reply]
```
alias: Energy - On Octopus Power Save Event
description: Turns export everything on the Powerwall during a Power Save event.
trigger:
  - platform: time
    at: input_datetime.octopus_saving_start
    id: start
    enabled: true
  - platform: time
    at: input_datetime.octopus_saving_end
    id: end
    enabled: true
  - platform: template
    value_template: >
      {{ now().replace(second=0, microsecond=0)|as_timestamp ==
      state_attr('input_datetime.octopus_saving_start', 'timestamp') - 1*60 }}

      # alternative method

      # {{ now().replace(second=0, microsecond=0) ==
      state_attr('input_datetime.octopus_saving_start', 'timestamp') |
      as_datetime - timedelta(minutes = 3) }}
    id: enable_export
  - platform: template
    value_template: >-
      {{ now().replace(second=0, microsecond=0) ==
      (states('input_datetime.octopus_saving_start')|as_datetime).replace(hour=15,
      minute=00)|as_local }}
    id: check_charge
  - platform: template
    value_template: >-
      {{ now().replace(second=0, microsecond=0) ==
      (states('input_datetime.octopus_saving_start')|as_datetime).replace(hour=15,
      minute=55)|as_local }}
    id: cease_charge
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - start
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.export_price_now
            data:
              value: |
                {{ input_number.octopus_saving_price }}
      - conditions:
          - condition: trigger
            id:
              - enable_export
        sequence:
          - service: select.select_option
            data:
              option: Everything
            target:
              entity_id: select.pied_bridge_cottage_energy_exports
      - conditions:
          - condition: trigger
            id:
              - end
        sequence:
          - service: select.select_option
            data:
              option: Solar
            target:
              entity_id: select.pied_bridge_cottage_energy_exports
          - service: automation.trigger
            target:
              entity_id: automation.house_set_electricity_cost
            data:
              skip_condition: true
      - conditions:
          - condition: trigger
            id:
              - check_charge
          - condition: numeric_state
            entity_id: sensor.powerwall_charge
            below: 95
        sequence:
          - service: number.set_value
            target:
              entity_id: number.pied_bridge_cottage_backup_reserve
            data:
              value: "100"
      - conditions:
          - condition: trigger
            id:
              - cease_charge
        sequence:
          - service: number.set_value
            target:
              entity_id: number.pied_bridge_cottage_backup_reserve
            data:
              value: "20"
mode: restart
```
