### DISCUSSION TITLE
Calculate next night lowest price

### DISCUSSION THREAD

**Discussion by luismsousa** [BottlecapDave/HomeAssistant-OctopusEnergy#864] [Q&A] [answered]
Hi there, 

I'm trying to create an automation to run after the next day rates are published and set a sensor with the lowest night time (00:00-06:00) Agile price so I can schedule devices to charge at that time.

I notice that the next day entity comes in the format of:
```
  - start: "2024-05-08T02:00:00+00:00"
    end: "2024-05-08T02:30:00+00:00"
    value_inc_vat: 0.15
    is_capped: false
```

Is there an easy way in HA to iterate over the time map and find the lowest price?

Cheers thanks!

**Comment by luismsousa** [comment]
So far, I've tried setting a helper template sensor with this template this but with no success:
```
{% set midnight = (today_at() + timedelta(days=1,)).isoformat() %}
{% set dawn = (today_at() + timedelta(days=1, hours=6)).isoformat() %}
{{ state_attr('event.octopus_energy_electricity_{meter info}_next_day_rates', 'rates') 
| selectattr('start', '>=', midnight) 
| selectattr('start', '<', dawn) 
| map(attribute='value_inc_vat') 
| min }}
```
this query does return the min value for the whole day:
```
{{ state_attr('event.octopus_energy_electricity_{meter info}_next_day_rates', 'rates') 
| map(attribute='value_inc_vat') 
| min }}
```

**Comment by BottlecapDave** [comment, marked as answer]
Hello. The easiest way would be to use a [target rate sensor](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/target_rate/), with a focus on 0.5 hours and a min-max time set to your desired period. This will turn on/off when the current rate is the cheapest rate. You could then use a template sensor to index into the first item of the `target_times` attribute. E.g.

```
{% set rates = state_attr('binary_sensor.octopus_energy_target_{{TARGET_RATE_NAME}}', 'target_times') %}
{% if rates is not none and rates | length > 0 %}
{{ rates[0]["value_inc_vat"] }}
{% endif %}
```

**Reply by luismsousa** [reply]
many thanks @BottlecapDave I was definitely trying to reinvent the wheel. 
That works like a charm ⭐

**Comment by luismsousa** [comment]
If anyone in the future comes looking for a way to set your house battery to charge at night for 3 periods of 30 mins, here's what I did. 
* Used the above target sensor with a focus of `2` (4 blocks of time, of which I'll choose the lowest 3 to charge).
* Set a helper template sensor called lowest_night_rate_next_day to fetch the 4th value in the array: 
```
{% set rates = state_attr('binary_sensor.octopus_energy_target_nighttime_rate', 'target_times') %}
{% if rates is not none and rates | length > 0 %}
{{ rates[3]["value_inc_vat"] }}
{% endif %}
```
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/1799045/cece5e58-a3b5-4503-a7d9-e9db6924d165)
* Set an automation that runs at 5pm and checks if the sensor value is below my export rate (in my case 15 pence) and sets a helper value that my inverter automation then polls to trigger the charge/discharge logic.
```
alias: Set night time charging price threshold
description: >-
  Check the next_day import rates and select the lowest price between 00:00 and
  06:00
trigger:
  - platform: time_pattern
    hours: "17"
    minutes: "00"
    seconds: "00"
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.lowest_night_rate_next_day
            below: 0.15
        sequence:
          - service: input_number.set_value
            metadata: {}
            data_template:
              entity_id: input_number.target_energy_price
              value: "{{ states('sensor.lowest_night_rate_next_day') }}"
    default:
      - service: input_number.set_value
        metadata: {}
        data:
          value: 0.15
        target:
          entity_id: input_number.target_energy_price
mode: single

```
