### DISCUSSION TITLE
Greenness Days

### DISCUSSION THREAD

**Discussion by bazcurtis** [BottlecapDave/HomeAssistant-OctopusEnergy#971] [General]
I only learnt about greenness days over the weekend. I have turned on sensor.octopus_energy_XXXXXXX_greenness_forecast_current_index. I am getting data, but I am not sure the best way to display it. Has anyone else started to look at greenness days?

**Comment by BottlecapDave** [comment]
Hello. There's a [community card](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/community/#greenness-forecast) which can be used to display the forecast.

**Reply by gcoan** [reply]
I use this apex chart to display the greenness forecast:

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: Greenness Forecast
graph_span: 7d
span:
  start: hour
apex_config:
  chart:
    height: 135
  stroke:
    width: 4
  xaxis:
    labels:
      format: ddd
series:
  - entity: sensor.octopus_energy_ACCOUNTNUM_greenness_forecast_current_index
    name: Forecast
    show:
      in_header: false
      legend_value: false
    color_threshold:
      - value: 0
        color: red
      - value: 40
        color: orange
      - value: 80
        color: green
    data_generator: |
      return entity.attributes.forecast.slice(0, 7).map((entry) => {
      return [new Date(entry.start), entry.greenness_score];
        });
```
