### ISSUE TITLE
Feature request: Service to re-evaluate target on demand

### ISSUE THREAD

**Issue by corvus2606** [BottlecapDave/HomeAssistant-OctopusEnergy#112]
Not sure how straightforward this would be, but I have a use case where I have a target set to run in the early morning, but want to use an Automation earlier in the evening to set charging times on my batteries(mostly so I can either choose to cancel it, or verify the time on the inverter)

From what I can see, the once a day targets seem to evaluate at midnight.  would it be possible to have a service to trigger the evaluation on demand?

**Comment by andyvirus** [comment]
I too would like to know if there is a method already, and if not then a feature for setting the evaluation time for targets. 

In my use case its for charging from agile slots, the cheaper the better. I am currently experimenting with intermittent target for x hours which should choose the y cheapest slots. 
The limitation is this only works after midnight and often there is cheap energy to be had about 23:00 which would be missed out on as im looking for the 8 cheapest slots prior to 9am before my solar panels can be used. 
So i have to add 00:00 to 09:00 as a boundary to the target sensor otherwise it may end up choosing 4 slots in the am and then another 4 in the pm as those were the cheapest in a 24 hour period… but not useful when i needed the battery full so not to be pulling from grid at peak times as 4 slots will not make it through the day.

So I would like the evaluation for sensors to occur at say 7pm so then i can tell the target sensor to turn on for each intermittent slot between 8pm and 8am. Technically I guess its possible to do that with two sensors but soon adds up to a large number of target sensors for different use cases.

If the eval time is hard coded, happy to just change there but would be nice if that was a variable that is exposed to HA as a gui option if possible.

**Comment by BottlecapDave** [comment]
These two are very interesting scenarios. While I think a service is probably the wrong way to go, it sounds like you want to force the evaluation to over night. Therefore I might look at doing something similar to Home Assistant and support where the end time can be set to "before" the start time (e.g. start time is 22:00 and end time is 05:00)

**Comment by andyvirus** [comment]
So for my scenario, and my apologies if i have hijacked your thread @corvus2606 but I think our desire for target rates evaluation to be variable is the same just from different angles. I apologise if I am wrong. For my scenario a picture is worth 1000 words.

![89608B72-3AE6-40BB-A8BE-2B07160DFC98](https://user-images.githubusercontent.com/11655424/210104583-17f0dfe3-d2b7-4d65-ba3d-d8206633b0c0.png)

You can see as the eval is midnight, my target rate of 4 hours intermittent would miss out on the cheap rates/negative rates prior to mid night. i have had to set start time to 00:00 and end to 09:00. This is so my battery is charged 100% before morning and not randomly throughout the day which with intermittent could and has left me pulling from grid at peak times as some were cheapest in the am and more in the pm. For me if the eval time was the same time the new rates for agile was published (4pm) or variable or after 4pm but before 00:00, i could charge from 8 cheap slots from 22:00 to 09:00. quite often the cheapest rates are in this range not after 00:00 only.

**Comment by corvus2606** [comment]
My use case is more so I can see the next time when i check in the evening, it's not necessarily to have a period run from after midnight until the next morning.  
That said, I think it would be very useful to have that ability, and I've learned to trust my setup and it hasn't failed me. robust automations ftw!

@andyvirus what are you using to populate the agile rates in that card?

**Comment by andynash** [comment]
> @andyvirus what are you using to populate the agile rates in that card?

That looks like the [Octopus Agile](https://github.com/markgdev/home-assistant_OctopusAgile) integration (I use it too).

@BottlecapDave The dev is no longer working on this, so you may find people coming from that integration to use this one (like myself!), and Agile-related features becoming more popular (as wholesale rates have fallen recently it makes more sense for those without the car/charger for Intelligent Octopus).

**Comment by andyvirus** [comment]
@andynash So what I use for that use case for my house battery (which will likely be 10x smaller than your car is full elec) is I have 1 automation that look for battery SOC % remaining, so below 30%, between 30 and 50, between 50 and 70, between 70 and 100. 

Each of the above is a "choice" condition in the Action of a single Automation. The Action for each choice is then to enable one of 4 further Automations. Depending on which automation is enabled by the above, determines how many "slots" is going to be used with the action of that to enable charging of the house battery. 

At 9am I then reset all 4 to disabled so when the midnight evaluation for target rates comes round, the selection is made once more.

So for each of the 4 automations, I have 4 Octopus Agile Target rates on Intermittent, number of hours (1 hour = 2 slots, and yes you can do 0.5 as I have tried) and start time 00:00 end time 09:00.
Intermittent will chose the BEST agile slots in that time frame (of time frame defined or it will default to 00:00 to 00:00 24 hours)

What I need is a way to set the time frame to 21:00 to 09:00 so that when the cheap night energy comes around I can charge using the 8 cheapest slots in that time frame. 

I can't use another 4 intermittent target rates from 21:00 to 00:00 as that fails to work and if I do 21:00 to 23:59, it does not include the slot at 23:30 to 00:00 which is often one of the cheapest. Even if I could I could end up charging the battery on slots that are expensive at night then when the 00:00 to 09:00 slot come round I have wasted money as potentialy the slot prior were more expensive than these... Hence the need to evaluate the entire block of slots from prior to midnight.

Hope that makes sense. While a service would be nice, I personally would like to be able to retain the logic of automations. Just need to figure how to factor Solar forecasting into this now so not to charge as much if x hours of solar is going to be available.

@corvus2606 see https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/88 for the rates card.

**Comment by andynash** [comment]
@andyvirus That all makes sense given what we have to work with right now.

If targets returned periods straddling midnight, that would clearly be more useful for overnight charging.

Our car is a hybrid so only 15kWh by the way, so usually we'd want to fill the battery, unless we know the next day will see little use and/or rates are very high. Sometimes we'd add a bit more during the day.

Regarding a service, that wouldn't be an alternative to automations, as an automation would call the service? It would simply make the result of your logic more accurate than your eg 30-40% range, by allowing you to specify an exact % instead. It would also reduce your automations to one.

For me, as things stand I'll probably need to create something myself, but targets would make things very much simpler, if they were able to straddle midnight and their options could be defined on demand.

**Comment by andyvirus** [comment]
ah that makes sense. yes if the service could take the input of battery soc and determine number of slots in a dynamic target, then yeah that would be awesome.

**Comment by andynash** [comment]
Well I was assuming the service would remain neutral - i.e. not be tied to any particular purpose like battery charging, but the automation would still be simple - here's an example:

```
description: ""
mode: single
trigger:
  - platform: time_pattern
    minutes: /30
condition:
  - condition: sun
    after: sunset
    before: sunrise
action:
  - service: octopus_energy.update_trigger [or some other means of updating a trigger]
    data: [all optional]
      hours: sensor.battery_charging_slots_needed [template: ( ( battery capacity - battery SOC ) / battery charge rate per hour ) | round(0,ceil)]
      start: input_select.battery_charge_from [19:30]
      end: input_select.battery_charge_by [09:00]
    target:
      entity_id: binary_sensor.charge_battery_trigger
  - if:
      - condition: state
        entity_id: binary_sensor.charge_battery_trigger
        state: "on"
    then:
      - service: homeassistant.turn_on
        data: {}
        target:
          entity_id: input_boolean.force_battery_charging
    else:
      - service: homeassistant.turn_off
        data: {}
        target:
          entity_id: input_boolean.force_battery_charging
```
