### ISSUE TITLE
Average Price for Target Sensor

### ISSUE THREAD

**Issue by dmelliott20** [BottlecapDave/HomeAssistant-OctopusEnergy#128]
Would it be possible to add an Average Price attribute to the target sensors.

Thanks

**Comment by BottlecapDave** [comment]
I'll add it to the list. It probably won't be a sensor but might appear as an attribute on the current rate sensor.

**Comment by dmelliott20** [comment]
Might not be explaining myself very well. I mean an average price for a target period.

So if the target sensor picks 3 slots with a price of 5p 10p and 15p the average for that target sensor would be 10p

Is that what you mean?

Thanks

Sent from my iPhone

On 21 Jan 2023, at 17:36, David Kendall ***@***.***> wrote:

﻿

I'll add it to the list. It probably won't be a sensor but might appear as an attribute on the current rate sensor.

**Comment by BottlecapDave** [comment]
Ok, sorry I misread the issue. Added to the list.

**Comment by adamwylde** [comment]
FYI @dmelliott20 if you are so inclined/in the meantime, you can do something like this with a template sensor to get the average rate for a given target (in my case called 'daytime'):

```
  - sensor:
      - name: "ElectricityDayRateAverageCost"
        state: "{{ state_attr('binary_sensor.octopus_energy_target_daytime','target_times') | sum(attribute='value_inc_vat') / (state_attr('binary_sensor.octopus_energy_target_daytime','Hours')*2) / 100 }}"
        icon: mdi:currency-gbp
```
