### ISSUE TITLE
Retrieve rate data for another tariff

### ISSUE THREAD

**Issue by sshaikh** [BottlecapDave/HomeAssistant-OctopusEnergy#1281]
### Describe the feature

A sensor that has rate information for a second tariff (ie one that you are not on).

### Expected behaviour

The same data as received for your actual tariff.

### Use Case

We are on agile, but it is useful to benchmark these rates so we can reason about the agile rates (eg if they are especially cheap). The Tracker tariff is a good candidate for this.

Non metered rates are available via the comparison sensor, however this is only for the previous day (by design).

### Confirmation

- [x] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [x] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. As mentioned in the [docs](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/tariff_comparison/) I have no plans to offer this as I'm trying to keep API calls to a minimum. I'm really curious though why the existing tariff comparison isn't good enough for this use case? You're not the first person to ask for this, but I don't see how having the data a day early would influence my decisions at all.

> Non metered rates are available via the comparison sensor, however this is only for the previous day (by design).

I'm not sure what you mean by "Non metered rates are available". Any tariff that is available via the API can be used with the tariff comparison tool. I use this to track agile and fixed tariffs while I am on a tracker tariff.

<img width="373" alt="Image" src="https://github.com/user-attachments/assets/6319e63c-fbc2-4e7a-8fd6-079bef482cf8" />

**Comment by sshaikh** [comment]
I did note that in the docs, and I didn't realise this would be more burdensome on the API than a comparison sensor. By "non-metered tariff" I meant "tariff that we are not on".

For the specific usecase:

I want to prepare a daily report for non technical users for them to make informed decisions about when to use energy (see #1275 ). The approach I landed on in that issue works quite well, however it uses a fixed price to determine what is "cheap". I've since realised that "cheap" is relative, and so I need something to benchmark the report against. I considered perhaps "lowest percentile" or something, but it occurred to me that the tracker rate for the same day serves as a good indication of what a good agile price might be for that day.

I was going to use the cost comparison to get that rate, but realised that it uses yesterday's cost (again, by design and which I understand and agree with) which wouldn't be relevant for today. Hence this request.

FWIW it's not a huge issue for tracker as a simple rest sensor should do the job for my specific use case.

**Comment by sshaikh** [comment]
If anyone was interested here's what I came up with:

```
sensor:
  - platform: rest
    resource_template: https://api.octopus.energy/v1/products/{{ states("input_text.octopus_tracker_product_code") }}/
    scan_interval: 31536000
    name: Octopus Tracker Electricity Daily Rate
    value_template: >
      {{ value_json['single_register_electricity_tariffs']['xxx']['direct_debit_monthly']['standard_unit_rate_inc_vat'] }}
```

where `input_text.octopus_tracker_product_code` holds the product code and `xxx` in the `value_template` is the location(?) code.

I then have an automation that calls `homeassistant.update_entity` on this sensor at 2am every morning.
