### ISSUE TITLE
Octopus Free Sessions not detected

### ISSUE THREAD

**Issue by PhillyGilly** [BottlecapDave/HomeAssistant-OctopusEnergy#1296]
### Describe the bug

Octopus Free Sessions were detected last year but no longer working

### Reproduction steps

I have enabled this sensor event.octopus_energy_a_bb74f479_octoplus_free_electricity_session_events.
These are its state attributes.
```
event_types:
  - octopus_energy_all_octoplus_free_electricity_sessions
friendly_name: Octoplus Free Electricity Session Events (A-BB74F479)
event_type: octopus_energy_all_octoplus_free_electricity_sessions
account_id: A-BB74F479
events:
  - code: "1"
    start: "2024-08-15T13:00:00+01:00"
    end: "2024-08-15T14:00:00+01:00"
    duration_in_minutes: 60
  - code: "2"
    start: "2024-08-18T13:00:00+01:00"
    end: "2024-08-18T14:00:00+01:00"
    duration_in_minutes: 60
  - code: "3"
    start: "2024-08-21T13:00:00+01:00"
    end: "2024-08-21T14:00:00+01:00"
    duration_in_minutes: 60
  - code: "4"
    start: "2024-08-31T13:00:00+01:00"
    end: "2024-08-31T14:00:00+01:00"
    duration_in_minutes: 60
  - code: "5"
    start: "2024-09-10T13:00:00+01:00"
    end: "2024-09-10T14:00:00+01:00"
    duration_in_minutes: 60
  - code: "6"
    start: "2024-09-14T13:00:00+01:00"
    end: "2024-09-14T14:00:00+01:00"
    duration_in_minutes: 60
  - code: "7"
    start: "2024-10-20T13:00:00+01:00"
    end: "2024-10-20T14:00:00+01:00"
    duration_in_minutes: 60
  - code: "8"
    start: "2024-11-24T07:00:00+00:00"
    end: "2024-11-24T09:00:00+00:00"
    duration_in_minutes: 120
```
Prices indicate that there is a free session today that is not detected as an event.

![Image](https://github.com/user-attachments/assets/d08cf8cf-79cc-448e-ae11-1d6a396d7ab9)

### Expected behaviour

I would expect today'r free session to be detected

### Tariff Code

sensor.octopus_energy_electricity_21l4045356_1170000688431_current_rate

### Integration Version

14.0.3

### Home Assistant Version

2025.4.4

### Fresh Install?

Not specified

### Home Assistant Logs

This is from my PredBat log 
2025-04-27 06:30:04.155355: Warn: record_status Bad date input_datetime.free_electricity_date provided in energy rates
2025-04-27 06:36:53.275351: Warn: Bad date input_datetime.free_electricity_date provided in energy rates
2025-04-27 06:36:53.311208: Warn: record_status Bad date input_datetime.free_electricity_date provided in energy rates
2025-04-27 06:40:03.521195: Warn: Bad date input_datetime.free_electricity_date provided in energy rates

### Confirmation

- [x] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [x] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)
