### ISSUE TITLE
Final refresh when the car disconnects

### ISSUE THREAD

**Issue by reedy** [BottlecapDave/HomeAssistant-OctopusEnergy#1316]
### Describe the feature

While https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/9db4551/_docs/blueprints/octopus_energy_manual_intelligent_refresh.yaml specifically refreshes when the car is plugged in, it doesn't do anything when the car is unplugged, meaning that dispatches can linger.

OE are pretty seemingly (currently?) pretty relaxed that when a dispatch has gone into a HH period, it seemingly bills at the cheaper rate, but I'm not sure we should eternally rely on this behaviour

### Expected behaviour

"Final" refresh of dispatches (with necessary delay) when the car is marked as no longer being plugged in.

### Use Case

I want HA to know that the car is disconnected, and as such, any dispatches need refreshing so that they're removed

### Confirmation

- [x] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [x] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment]
Hello. Thanks for the suggestion. I'm not sure when I'll get to it, but feel free to raise a pr with the change if you have in mind how it should work.

**Comment by reedy** [comment]
On a state change to car not plugged in... wait 30s and then do a refresh?

I guess it just gets a bit more complex as the conditions currently check that the car is plugged in.

**Comment by reedy** [comment]
I did this locally a little while ago for this reason...

```yaml
alias: Refresh intelligent dispatches upon EV Disconnect
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.myenergi_zappi_1234567890_plug_status
    to: EV Disconnected
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: octopus_energy.refresh_intelligent_dispatches
    target:
      entity_id: binary_sensor.octopus_energy_a_12345678_intelligent_dispatching
    data: {}
mode: single
```
