### ISSUE TITLE
Rolling Target Not Updating

### ISSUE THREAD

**Issue by sshaikh** [BottlecapDave/HomeAssistant-OctopusEnergy#1336]
### Describe the bug

Two identical (at least via configuration) rolling targets are configured, yet only one evaluates

### Reproduction steps

Create a new rolling target with the same configuration as an existing one. See that a window isn't created.

### Expected behaviour

For an evaluation to occur.

### Tariff Code

 E-1R-AGILE-24-04-03-C

### Integration Version

1.1.1

### Home Assistant Version

2025.4.4

### Fresh Install?

After upgrading

### Home Assistant Logs

Nothing in logs but here are the respective attributes. These were extracted at 2025-06-05T12:04:+01:00

Working:
```
name: 10_hours
hours: 1
hours_mode: exact_hours
type: Continuous
look_ahead_hours: 24
target_times_evaluation_mode: always
kind: rolling_target_rate
target_times: 
- start: '2025-06-05T14:30:00+01:00'
  end: '2025-06-05T15:00:00+01:00'
  value: 0.1092
  metadata:
    is_capped: false
- start: '2025-06-05T15:00:00+01:00'
  end: '2025-06-05T15:30:00+01:00'
  value: 0.103215
  metadata:
    is_capped: false

target_times_last_evaluated: 2025-06-04T23:29:45.607991+01:00
time_periods_incomplete: true
overall_average_value: 0.10621
overall_min_value: 0.103215
overall_max_value: 0.1092
current_duration_in_hours: 0
current_average_value: null
current_min_value: null
current_max_value: null
next_time: 2025-06-05T14:30:00+01:00
next_duration_in_hours: 1
next_average_value: 0.10620750000000001
next_min_value: 0.103215
next_max_value: 0.1092
icon: mdi:camera-timer
friendly_name: 10_hours (octopus_energy_import)
```

Not working:
```
name: rollling_test
hours: 1
hours_mode: exact_hours
type: Continuous
look_ahead_hours: 24
target_times_evaluation_mode: always
kind: rolling_target_rate
rolling_target: true
latest_values: false
time_periods_incomplete: true
overall_average_value: 0
overall_min_value: null
overall_max_value: null
current_duration_in_hours: 0
current_average_value: null
current_min_value: null
current_max_value: null
next_time: null
next_duration_in_hours: 0
next_average_value: null
next_min_value: null
next_max_value: null
icon: mdi:camera-timer
friendly_name: rollling_test (octopus_energy_import)
```

### Confirmation

- [x] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [x] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)
