### ISSUE TITLE
`next_time` is miscalculated, `offset` seems doubled

### ISSUE THREAD

**Issue by mateuszdrab** [BottlecapDave/HomeAssistant-OctopusEnergy#169]
**Describe the bug**

I have created a sensor with `offset: '-3:00:00'`, the first target time starts at `2023-03-13T03:00:00+00:00` but the calculated `next_time` is `2023-03-12T21:00:00+00:00`.
Also reproduced it with offset `-01:00:00` where the next time was 2 hours instead of 1 hour early compared to the first target_rate time.
Without `offset`, `next_time` is correctly at 3:00.

**Expected behavior**

I expected the `next_time` to  be `2023-03-13T00:00:00+00:00`

**Home Assistant Version**

2023.3.3

**Integration Version**

v6.0.1

**Fresh Install?**

Fresh

**Home Assistant Logs**

Full sensor data:

```
Name: night_laundry
Hours: 5
Type: Continuous
rolling_target: false
Start time: '0:00'
End time: '9:00'
offset: '-3:00:00'
is_target_export: false
target_times:
  - value_inc_vat: 5.628
    valid_from: '2023-03-13T03:00:00+00:00'
    valid_to: '2023-03-13T03:30:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 1.0185
    valid_from: '2023-03-13T03:30:00+00:00'
    valid_to: '2023-03-13T04:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 5.0715
    valid_from: '2023-03-13T04:00:00+00:00'
    valid_to: '2023-03-13T04:30:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 3.6855
    valid_from: '2023-03-13T04:30:00+00:00'
    valid_to: '2023-03-13T05:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 4.431
    valid_from: '2023-03-13T05:00:00+00:00'
    valid_to: '2023-03-13T05:30:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 16.5375
    valid_from: '2023-03-13T05:30:00+00:00'
    valid_to: '2023-03-13T06:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 13.4505
    valid_from: '2023-03-13T06:00:00+00:00'
    valid_to: '2023-03-13T06:30:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 26.901
    valid_from: '2023-03-13T06:30:00+00:00'
    valid_to: '2023-03-13T07:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 19.5825
    valid_from: '2023-03-13T07:00:00+00:00'
    valid_to: '2023-03-13T07:30:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
  - value_inc_vat: 25.242
    valid_from: '2023-03-13T07:30:00+00:00'
    valid_to: '2023-03-13T08:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-BB-23-02-08-H
next_time: '2023-03-12T21:00:00+00:00'
current_duration_in_hours: 0
next_duration_in_hours: 5
icon: mdi:camera-timer
friendly_name: Octopus Energy Target night_laundry

```

I'd like to know if this is a bug or am I doing something wrong?
