### ISSUE TITLE
Statistics not enabled for monetary sensors

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#220]
@BottlecapDave could I please request enabling statistics for these sensors? This is so the rates can be recorded indefinitely and plotted more cheaply than life data. Currently only one entity shows up in the Developer Tools/Statistics section.

Guidelines from HA:
https://www.home-assistant.io/more-info/statistics/
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

_Originally posted by @andrzej-r in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/145#issuecomment-1513299895_

**Comment by andrzej-r** [comment]
Thanks for setting up the ticket.

I think you meant `sensor.electricity_<number>_<number>_previous_accumulative_consumption/cost` entities, which indeed are of `state_class: total` type with reset. The entities I was after, though, are `sensor.electricity_<number>_<number>_current_rate`. I would like to track/plot them over a longer period of time but they have no `state_class: measurement` definitions included and they are marked as `device_class: monetary`, which [apparently](https://developers.home-assistant.io/docs/core/entity/sensor/#entities-not-representing-a-total-amount) is at odds with the former.

**Comment by BottlecapDave** [comment]
Sorry for the late response and thanks for the clarification which entities you're were referring to. When you said "Currently only one entity shows up" I was confused as this was not the case.

When I set up the entites originally they were based on descriptions laid out at https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes, where the reported data wasn't an accumulation which is why measurement was picked. 

However looking at other monetary sensors within HA Core, others have picked total or total_increasing. I will look at changing this, however I know HA doesn't like when state classes change so will need to make sure it doesn't have any unintended consequences.

**Comment by andrzej-r** [comment]
Thanks for looking into it. Actually, `state_class: measurement` makes perfect sense to me (as far as I can see state_class is currently undefined). It is just for whatever reason HA assumes `device_class: monetary` cannot be a measurement. Probably because in HA "monetary" is assumed to be a monetary balance, not a monetary rate.

**Comment by BottlecapDave** [comment]
This should now be fixed in the latest release (v7.1.0)

**Comment by andrzej-r** [comment]
@BottlecapDave, I can see these `*current_rate` entities in Developer Tools->Statistics but they are listed as total (accumulative) quantities. Philosophy aside, it means they only expose "sum", "state" and "change" statistics and not the usual "mean", "min", "max" one would expect from measurements. The easiest way to inspect it is to try adding the entities to a Statistics Graph Card.

Would it be possible to convert them into `state_class: measurement` and remove/change `device_class: monetary`? Not sure what `device_class` should be used in this case - ideally that would be "cost" or "monetary_rate" but I do not see them on the list of standard device classes.

**Comment by andrzej-r** [comment]
I forgot to thank you for this fix. I could plot these rates by using a "state" statistic. This may not be my preferred solution but it did the job.

**Comment by andrzej-r** [comment]
For others who may need this feature. Min/Max/Mean statistics can be added on HA side by creating new/derived template sensors:
```yaml
template:
  - sensor:
      - name: "Electricity Rate Import"
        unit_of_measurement: "GBP/kWh"
        state_class: "measurement"
        icon: "mdi:currency-gbp"
        state: "{{ states('sensor.electricity_*_*_current_rate')|float }}"
      - name: "Electricity Rate Export"
        unit_of_measurement: "GBP/kWh"
        state_class: "measurement"
        icon: "mdi:currency-gbp"
        state: "{{ states('sensor.octopus_energy_electricity_*_*_export_current_rate')|float }}"
      - name: "Gas Rate"
        unit_of_measurement: "GBP/kWh"
        state_class: "measurement"
        icon: "mdi:currency-gbp"
        state: "{{ states('sensor.gas_*_*_current_rate')|float }}"
      - name: "Electricity Standing Charge Import"
        unit_of_measurement: "GBP"
        state_class: "measurement"
        icon: "mdi:currency-gbp"
        state: "{{ states('sensor.electricity_*_*_current_standing_charge')|float }}"
      - name: "Electricity Standing Charge Export"
        unit_of_measurement: "GBP"
        state_class: "measurement"
        icon: "mdi:currency-gbp"
        state: "{{ states('sensor.octopus_energy_electricity_*_*_export_current_standing_charge')|float }}"
      - name: "Gas Standing Charge"
        unit_of_measurement: "GBP"
        state_class: "measurement"
        icon: "mdi:currency-gbp"
        state: "{{ states('sensor.gas_*_*_current_standing_charge')|float }}"
```
