### ISSUE TITLE
Allow Agile Octopus Tracking for non-user

### ISSUE THREAD

**Issue by JRascagneres** [BottlecapDave/HomeAssistant-OctopusEnergy#294]
**Describe the feature**

Essentially I'm considering getting agile octopus but would like to track the costs for a while into home assistant so I can calculate whether this would be worth-while for me.  It would be quite nice if we could opt to have the agile octopus stats as sensors even though thats not what our account is using. This would be in addition to the existing account sensors.

**Comment by JRascagneres** [comment]
So I can enable this override without affecting the other sensors which have my 'true' data?

**Comment by BottlecapDave** [comment]
Correct if you enable them they'll create additional sensors for your previous consumption which represents the override. You then do something like the following to compare your current tariff with your comparison tariff

```yaml
chart_type: line
period: hour
type: statistics-graph
entities:
  - >-
    sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_cost
  - >-
    sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_cost_override
stat_types:
  - state
```
