### ISSUE TITLE
Binary Sensor to send notification in advance of operation.

### ISSUE THREAD

**Issue by Jonaz80** [BottlecapDave/HomeAssistant-OctopusEnergy#416]
**Describe the feature**

Send a notification when new rates published of when a binary sensor will start/stop.  

Use case:  dishwasher on/off is momentary switch but start can be delayed by the user.  This advanced/ 'heads-up' notification message would allow recipients to know the correct time to set delay to get lowest overnight price for the dishwasher cycle.

**Expected behavior**
- Trigger: Tomorrow's rates published
- binary 'notification' sensor run time calculated
- notification sent via mobile app containing start/stop times that meet the conditions of the sensor, or a use configurable message with these times as values that can be added to the message with whatever formatting the user chooses.

**Comment by BottlecapDave** [comment]
Hello. If I understand your scenario correctly, a new sensor isn't needed as you can do this with existing HA functionality. The times for when the sensor is due can be found as [attributes](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_target_rate.md#attributes) on the sensor. 

I for instance have a template sensor which extracts this time out

```
vacuum_time:
      friendly_name: Vacuum time
      icon_template: mdi:clock
      value_template: >-
        {{ as_local(state_attr("binary_sensor.octopus_energy_target_vacuum", "next_time")).strftime('%H:%M')  }}
```

and then I have an automation that sends an alert at a specific time to tell me when my vacuum is due on

```
- alias: Cleaning - Clean house notice
  trigger:
  - platform: event
    event_type: morning_reminder
  condition:
    - condition: state
      entity_id: input_boolean.is_cleaning_scheduled
      state: 'on'
  action:
  - event: notify_channels
    event_data_template:
      mode: speaker
      title: Cleaning occurring
      message: >
          {{ [
            "I'm due to clean today at " + states("sensor.vacuum_time") + ". If you don't want this, ask me to 'turn off cleaning'.",
            "I'll be cleaning today at " + states("sensor.vacuum_time") + ". If it's not convenient, ask me to 'turn off cleaning'.",
          ] | random }}
```

If you're wanting to send an alert x minutes before then I have a template sensor which stores the datetime the notification should go off

```
vacuum_warning_one:
      friendly_name: "Vacuum warning one"
      device_class : timestamp
      value_template: >-
        {% set date = state_attr("binary_sensor.octopus_energy_target_vacuum_working_hours", "next_time") %}
        {% if date != None %}
        {{ date - timedelta( minutes = 30 ) }}
        {% else %}
        {{ as_datetime("2021-01-01T00:00Z") }}
        {% endif %}
```

and then an automation looks like
```
- alias: Cleaning - Clean house warning
  trigger:
  - platform: time
    at: sensor.vacuum_warning_one
  condition:
    - condition: state
      entity_id: input_boolean.is_cleaning_scheduled
      state: 'on'
  action:
  - event: notify_channels
    event_data_template:
      mode: speaker
      title: Cleaning occurring
      message: >
        {% set target_time = as_local(state_attr("binary_sensor.octopus_energy_target_vacuum", "next_time")) %}
 
        {% set minutes = ((as_timestamp(target_time) - as_timestamp(now())) / 60) | round(0) %}
        {{ [
          "I'm planning to clean the house in " + minutes|string + " minutes. If you don't want this, ask me to 'turn off cleaning'.",
          "I'll be cleaning the house in " + minutes|string + " minutes. If it's not convenient, ask me to 'turn off cleaning'.",
          ] | random }}
```

As you can see I use an input boolean to determine if the vacuum should go on or not, which I use as a condition for an automation when triggering the vacuum

```
- alias: Cleaning - Start Automatic While Everyone Out (Non Work Day)
  id: 5418B9B8-3B54-49A2-8DCA-C9846B67F751
  trigger:
  - platform: state
    entity_id: binary_sensor.octopus_energy_target_vacuum
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.is_cleaning_scheduled
      state: 'on'
  action:
  - event: start_cleaning
```

Let me know if I've misunderstood your scenario.
