### ISSUE TITLE
Wheel of fortune spin support

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/HomeAssistant-OctopusEnergy#431]
**Describe the feature**

A sensor for electricity and gas to determine how many wheel of fortune spins are remaining

A service to support executing a wheel of fortune spin. Should return the amount won.

**Expected behavior**

With these sensors, it should then be possible to configure automations to automatically execute the wheel of fortune spins and do something off the back if money is won

**Comment by andyblac** [comment]
has anyone ever won anything ?

**Comment by BottlecapDave** [comment]
I think I won a £1 once :p

**Comment by owenashurst** [comment]
There's no API for the wheel of fortune from Octopus's API.

**Comment by BottlecapDave** [comment]
There is, it's just not available under the REST API. The feature will be available in the next release.

**Comment by owenashurst** [comment]
> There is, it's just not available under the REST API. The feature will be available in the next release.

Oh really? Have you got a link to it? I don't see it on their docs here:
https://developer.octopus.energy/docs/api/

**Comment by BottlecapDave** [comment]
It uses their graphql API, which is self documenting. The queries can be found at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/custom_components/octopus_energy/api_client/__init__.py#L265

**Comment by aaron-trout** [comment]
Thanks for implementing this @BottlecapDave 

I tried to use the automation provided in services.md but I cant get it to work. The problem seems to be with the `{{ trigger.entity_id }}` in the action; I can't see any docs on `trigger` in the templating; it seems to not exist unless I am missing something 🤔 

Any thoughts / would you be able to update the doc there with some more info?

Thanks!

**Comment by BottlecapDave** [comment]
[Trigger variables](https://www.home-assistant.io/docs/automation/templating#numeric-state) are available via all automations. I'm not sure if the UI is interpreting something odd in the automation. The only thing I can suggest (and I'll update the docs) is to have two separate automations

```yaml
- alias: OE - Spin Gas Wheel Of Fortune
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.octopus_energy_xxx_wheel_of_fortune_spins_gas
      above: 0
  condition: []
  action:
    - repeat:
        count: >
          {{ states('sensor.octopus_energy_xxx_wheel_of_fortune_spins_gas') | int }}
        sequence:
          - service: octopus_energy.spin_wheel_of_fortune
            data: {}
            target:
              entity_id: >
                {{ 'sensor.octopus_energy_xxx_wheel_of_fortune_spins_gas' }}
```

```yaml
- alias: OE - Spin Electricity Wheel Of Fortune
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.octopus_energy_xxx_wheel_of_fortune_spins_electricity
      above: 0
  condition: []
  action:
    - repeat:
        count: >
          {{ states('sensor.octopus_energy_xxx_wheel_of_fortune_spins_electricity') | int }}
        sequence:
          - service: octopus_energy.spin_wheel_of_fortune
            data: {}
            target:
              entity_id: >
                {{ 'sensor.octopus_energy_xxx_wheel_of_fortune_spins_electricity' }}
```

**Comment by andyblac** [comment]
> Thanks for implementing this @BottlecapDave
> 
> I tried to use the automation provided in services.md but I cant get it to work. The problem seems to be with the `{{ trigger.entity_id }}` in the action; I can't see any docs on `trigger` in the templating; it seems to not exist unless I am missing something 🤔
> 
> <img alt="Screenshot 2023-11-25 at 11 05 18" width="1073" src="https://private-user-images.githubusercontent.com/2394679/285587007-c2e4ca39-a09c-4c50-a6aa-66321bc6dffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTA2MzYsIm5iZiI6MTcwMDkxMDMzNiwicGF0aCI6Ii8yMzk0Njc5LzI4NTU4NzAwNy1jMmU0Y2EzOS1hMDljLTRjNTAtYTZhYS02NjMyMWJjNmRmZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjVUMTEwNTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUxOGRiYjE5MmQ4ZDE1YjQxZTkxMzIyNjA5M2ZmYzMxNzc5OWJjMThlYzk1NzA0OTAxMDJhMzVkOWQzODZiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0CKKMpFUHZlHKx2g8ueo7Fki0v56RK4GHrHQlExNXdE">
> Any thoughts / would you be able to update the doc there with some more info?
> 
> Thanks!

try this 
```
repeat:
  count: '{{ states(trigger.entity_id) | int }}'
  sequence:
    - service: octopus_energy.spin_wheel_of_fortune
      data: {}
      target:
        entity_id: '{{ trigger.entity_id }}'
```

**Comment by BottlecapDave** [comment]
@aaron-trout Let me know which one of the above works for you (trigger would be preferable) and I'll update the docs. I can't test at the moment unfortunately as I have no spins left for this month

**Comment by andyblac** [comment]
> @aaron-trout Let me know which one of the above works for you (trigger would be preferable) and I'll update the docs. I can't test at the moment unfortunately as I have no spins left for this month

in that case try:

```
- alias: OE - Spin Wheel Of Fortune
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.octopus_energy_xxx_wheel_of_fortune_spins_electricity
      above: 0
    - platform: numeric_state
      entity_id: sensor.octopus_energy_xxx_wheel_of_fortune_spins_gas
      above: 0
  condition: []
  action:
    - repeat:
        count: '{{ states(trigger.entity_id) | int }}'
        sequence:
          - service: octopus_energy.spin_wheel_of_fortune
            data: {}
            target:
              entity_id: '{{ trigger.entity_id }}'
```
