### ISSUE TITLE
Home mini refresh rate stops target sensors  updating

### ISSUE THREAD

**Issue by f1wade** [BottlecapDave/HomeAssistant-OctopusEnergy#435]
### Describe the bug

I have a target sensor that will trigger 2 half hours overnight.
Worked fine at 1 min refresh rate.
I changed to 10 min refresh rate, to save network calls.
And the trigger didn't trigger at all overnight and it should have turned on, off, on, off. For half hour each.

I have changed back to 2 mins, to see if that works better. 

### Reproduction steps

As above

### Expected behaviour

To update correctly. 

### Integration Version

Latest

### Home Assistant Version

2023.7.3

### Fresh Install?

Not specified

### Home Assistant Logs

Will see if any later

**Comment by f1wade** [comment]
1 other thing that changed on the target was I ticked last applicable rates, I've not had that ticked through a cycle.

**Comment by f1wade** [comment]
Update I change to 2 mins and it worked, and then 5 mins and it worked.

**Comment by BottlecapDave** [comment]
Hello and sorry you're having issues. I believe the updating of the mini rates are just a coincidence as the two settings are unrelated. I have sporadic reports of sensors stopping working, which I'm still trying to track down the cause for.

**Comment by f1wade** [comment]
If I can help let me know.

**Comment by f1wade** [comment]
@BottlecapDave what is it that updates these target sensors?
Ie Internet connection for timer,
Octopus rate updating, timer based on the target sensor times.

Wondering if Internet connection or network interruptions will affect it firing?

**Comment by BottlecapDave** [comment]
The integration relies on HA to check the state every minute. The rate information is retrieved in the background using HA reccommmended approaches. I'm already catching any exceptions so lack of internet connections shouldn't effect it. I've made some changes in the latest release which will hopefully make this more reliable.

**Comment by stefano-bortolotti** [comment]
Hi @BottlecapDave, I've installed the home mini device yesterday by going to the "Octopus Energy" integration in HA and ticking the "I have a mini ..." checkbox. 
Today I noticed the since yesterday all my target sensors have stopped working(as in they don't trigger my automations) and I've not yet found the reason. 
The target sensors shows the correct data, example: 
```
Name: water_heater_morning_schedule
Hours: 1.5
Type: Intermittent
MPAN: '1030034828671'
rolling_target: false
last_rates: true
Start time: '02:30'
End time: '08:30'
kind: target_rate
is_target_export: false
target_times:
  - value_inc_vat: 0
    valid_from: '2023-10-06T02:00:00+00:00'
    valid_to: '2023-10-06T02:30:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-22-11-25-A
    is_capped: false
  - value_inc_vat: 0.063
    valid_from: '2023-10-06T02:30:00+00:00'
    valid_to: '2023-10-06T03:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-22-11-25-A
    is_capped: false
  - value_inc_vat: 0
    valid_from: '2023-10-06T03:30:00+00:00'
    valid_to: '2023-10-06T04:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-22-11-25-A
    is_capped: false
overall_average_cost: 0.021p
overall_min_cost: 0.0p
overall_max_cost: 0.063p
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: '2023-10-06T02:00:00+00:00'
next_duration_in_hours: 1
next_average_cost: 0.0315p
next_min_cost: 0.0p
next_max_cost: 0.063p
icon: mdi:camera-timer
friendly_name: Octopus Energy Target water_heater_morning_schedule

```
but the automation trigger is not triggered at the listed times, my trigger YMAL: 
```
platform: template
value_template: >-
  {% if
  is_state('binary_sensor.octopus_energy_target_water_heater_morning_schedule',
  'on') %}
    True
  {% else %}
    False
  {% endif %}
for:
  hours: 0
  minutes: 0
  seconds: 15
```
Reading the above thread I wonder if the mini is related to the issue I'm experiencing since the change coincides with the triggers issue. 
Let me know if I can provide more info. 
Thanks
