### ISSUE TITLE
Non-existent saving session

### ISSUE THREAD

**Issue by alfwro13** [BottlecapDave/HomeAssistant-OctopusEnergy#612]
### Describe the bug

This relates to the saving session as described in Issue #561 . I have followed up with Octopus regarding that session and they told me that they didn't have a saving session on that date. 
At the time the saving session id was 1164. However now when I check the event.octopus_energy_<account_id>_octoplus_saving_session_events sensor attributes I can see that id 1164 is no longer there:
````
event_types: octopus_energy_all_octoplus_saving_sessions
event_type: octopus_energy_all_octoplus_saving_sessions
account_id: <account_id>
available_events: 
joined_events: 
- id: 1163
  start: '2023-11-16T17:30:00+00:00'
  end: '2023-11-16T18:30:00+00:00'
  rewarded_octopoints: 3120
  octopoints_per_kwh: 1800
- id: 1165
  start: '2023-11-29T17:00:00+00:00'
  end: '2023-11-29T18:30:00+00:00'
  rewarded_octopoints: 8296
  octopoints_per_kwh: 3200
````
### Reproduction steps

Enroll to a saving session

### Expected behaviour

Enroll to a saving session only if it actually exists

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-J

### Integration Version

at the time when experienced that issue: 9.0.1

### Home Assistant Version

at the time when experienced that issue:  2023.11.3

### Fresh Install?

After upgrading

### Home Assistant Logs

none

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs)
- [X] I confirm that I cannot find my solution within the [FAQ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/tree/develop/_docs/faq.md)
