### ISSUE TITLE
Monthly costs with utility sensors not being calculated correctly anymore

### ISSUE THREAD

**Issue by badguy99** [BottlecapDave/HomeAssistant-OctopusEnergy#620]
I had this set up, basically as above (different offset day due to when my billing is). However, since v9.0.0 the cost seem to increase every 30 minutes, rather than daily, which is ballooning the reported monthly cost. I'm currently running v9.0.2 and still see the issue.

_Originally posted by @badguy99 in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/296#discussioncomment-7682787_

**Comment by BottlecapDave** [comment]
Hello. Sorry for not responding sooner, but I was waiting for December to trick over and reset the utility meter and then forgot.

You'll need to update the utility meter (or create a new one) with the following configuration

```
monthly_electricity_cost:
  source: sensor.octopus_energy_electricity_xxx_xxx_previous_accumulative_cost
  name: Monthly Electricity Cost
  cycle: monthly
  offset:
    # At least one of these must be specified:
    days: 1
```

The key part is you need to target the accumulative sensors and therefore not have `delta` enabled.

Unfortunately with some new attributes added to the non accumulative sensor and no way of only focusing on state changes (like automations), it's not suited for utility meters.
