### ISSUE TITLE
Target Rate Sensors no longer updating in time for Agile after updating to v9.1.0

### ISSUE THREAD

**Issue by alexhk90** [BottlecapDave/HomeAssistant-OctopusEnergy#644]
### Describe the bug

Target Rate Sensor entities that were working on v8.4 with the Agile tariff are no longer working on v9.1.0. 
In the last couple of days (since updating from v8.4 to v9.1.0), these entities have been "off" for the whole day. 

Looking at one of these entities in the "States" tab under "Developer tools" (current time is 2023-12-19 11:30), it appears that the update for the new rates did not occur yesterday: 
```
rolling_target: false
last_rates: true
kind: target_rate
is_target_export: false
target_times: 
- value_inc_vat: 0.10689
  start: '2023-12-18T02:00:00+00:00'
  end: '2023-12-18T02:30:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-C
  is_capped: false
- value_inc_vat: 0.0777
  start: '2023-12-18T02:30:00+00:00'
  end: '2023-12-18T03:00:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-C
  is_capped: false

overall_average_cost: 0.0923
overall_min_cost: 0.0777
overall_max_cost: 0.10689
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: 2023-12-18T02:00:00+00:00
next_duration_in_hours: 1
next_average_cost: 0.092295
next_min_cost: 0.0777
next_max_cost: 0.10689
icon: mdi:camera-timer
friendly_name: Octopus Agile Target Water Boiler Morning
target_invert_target_rates: false
target_times_last_evaluated: 2023-12-17T22:39:24.517815+00:00
last_evaluated: 2023-12-17T22:46:24.635701+00:00
name: target_waterboiler_morning
hours: 1.0
type: Continuous
start_time: 01:30
end_time: 06:30
mpan: <removed>
account_id: <removed>
```

Looking at the attributes day rates entities, "Current Day Rates" is populated but "Next Day Rates" is not (probably expected as it's not yet 4pm, but perhaps the change to these entities is related). 

Reading the FAQ, this appears to describe the issue: 
https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#why-wont-my-target-rates-update

### Reproduction steps

Configure Target Rate sensors for Agile tariff following the instructions (including on start/end times) as described in the documentation: 
https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/target_rate/

### Expected behaviour

Target Rate sensors should update for next/current day as rates are updated. 

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-C

### Integration Version

9.1.0

### Home Assistant Version

2023.12.3

### Fresh Install?

After upgrading

### Home Assistant Logs

(enabled debug logging as per readme; will look to update/add in next couple of days if would be helpful to diagnose)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)
