### ISSUE TITLE
Target Rate Binary Sensors Not Turning on at selected time

### ISSUE THREAD

**Issue by Daverover66** [BottlecapDave/HomeAssistant-OctopusEnergy#764]
### Describe the bug

This integration has been working flawlessly for months now.  However, something happened when Octopus changed their standing charge rates a couple of days ago and when I updated HA to 2024.2.1 and this integration to 10.1.0

I have 6 target rate sensors, 2 of which are not turning on when they reach the selected time.  Here is one such target rate sensor where you can clearly see that 6 rates were selected covering a 3 hour period between 3am and 6am. 

```
name: intermittent_best_rates_3_hours_overnight
hours: "3.0"
type: Intermittent
mpan: "*******************"
rolling_target: true
last_rates: true
target_invert_target_rates: false
start_time: "21:00"
end_time: "08:00"
kind: target_rate
account_id: ***************
is_target_export: false
rates_incomplete: false
target_times:
  - value_inc_vat: 0.120855
    start: "2024-02-17T03:00:00+00:00"
    end: "2024-02-17T03:30:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.120855
    start: "2024-02-17T03:30:00+00:00"
    end: "2024-02-17T04:00:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.120855
    start: "2024-02-17T04:00:00+00:00"
    end: "2024-02-17T04:30:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.120855
    start: "2024-02-17T04:30:00+00:00"
    end: "2024-02-17T05:00:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.120855
    start: "2024-02-17T05:00:00+00:00"
    end: "2024-02-17T05:30:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.120855
    start: "2024-02-17T05:30:00+00:00"
    end: "2024-02-17T06:00:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
target_times_last_evaluated: "2024-02-16T16:51:09.342491+00:00"
overall_average_cost: 0.12086
overall_min_cost: 0.120855
overall_max_cost: 0.120855
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: "2024-02-17T03:00:00+00:00"
next_duration_in_hours: 3
next_average_cost: 0.120855
next_min_cost: 0.120855
next_max_cost: 0.120855
last_evaluated: "2024-02-16T20:51:11.329478+00:00"
icon: mdi:camera-timer
friendly_name: Octopus Energy Target intermittent_best_rates_3_hours_overnight
```
This is the history of all target rate sensors over the last 24 hours. The sensor shown above is third one down.

![Screenshot_20240217_085338_Home Assistant](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/109820608/b2b9d89b-b1d9-49de-b938-f0da7e4f5641)

This has happened for 2 nights in a row now.
 
I don't often raise issues so I hope I've given you enough to go on.

In the meantime, I'm going to create another target rate sensor that covers the next few hours and watch what it does.  

### Reproduction steps

Create a target rate sensor as above and monitor the binary sensor's behaviour over the target times.

### Expected behaviour

I expect the target rate binary sensors to turn on at the start of a target rate period and off at the end. 

### Tariff Code

E-1R-AGILE-23-12-06-N

### Integration Version

10.1.0

### Home Assistant Version

Core: 2024.2.1

### Fresh Install?

After upgrading

### Home Assistant Logs

Diagnostics json as follows:
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.2.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.1",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.74-haos",
    "supervisor": "2024.01.1",
    "host_os": "Home Assistant OS 11.5",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hildebrandglow_dcc": {
      "version": "1.0.3",
      "requirements": [
        "pyglowmarkt==0.5.5"
      ]
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "thermal_comfort": {
      "version": "2.2.2",
      "requirements": []
    },
    "skyq": {
      "version": "v2.11.7",
      "requirements": [
        "pyskyqremote==0.3.26"
      ]
    },
    "octopus_energy": {
      "version": "10.1.0",
      "requirements": []
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "battery_notes": {
      "version": "2.0.16",
      "requirements": []
    },
    "feedparser": {
      "version": "0.1.11",
      "requirements": [
        "feedparser==6.0.10"
      ]
    },
    "sonoff": {
      "version": "3.5.4",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "smartlife": {
      "version": "0.1.0",
      "requirements": [
        "tuya-device-sharing-sdk==0.1.9"
      ]
    },
    "tapo_control": {
      "version": "5.4.13",
      "requirements": [
        "pytapo==3.3.18"
      ]
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "frigate": {
      "version": "5.0.1",
      "requirements": [
        "pytz==2022.7"
      ]
    },
    "dwains_dashboard": {
      "version": "3.4.3",
      "requirements": []
    },
    "tuya_local": {
      "version": "2024.2.0",
      "requirements": [
        "tinytuya==1.13.1"
      ]
    },
    "govee": {
      "version": "2023.11.1",
      "requirements": [
        "govee-api-laggat==0.2.2",
        "dacite==1.8.0"
      ]
    },
    "alexa_media": {
      "version": "4.9.2",
      "requirements": [
        "alexapy==1.27.10",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "homelink": {
      "version": "v1.3.7",
      "requirements": [
        "pyhomelink==0.1.9",
        "paho-mqtt==1.6.1"
      ]
    },
    "adaptive_lighting": {
      "version": "1.20.0",
      "requirements": [
        "ulid-transform"
      ]
    },
    "better_thermostat": {
      "version": "1.4.0",
      "requirements": []
    },
    "homewhiz": {
      "version": "0.0.6",
      "requirements": [
        "bleak",
        "bleak_retry_connector",
        "dacite",
        "aiohttp",
        "bidict"
      ]
    },
    "solaredge_modbus_multi": {
      "version": "2.4.11-pre.6",
      "requirements": [
        "pymodbus>=3.5.4"
      ]
    },
    "spook_inverse": {
      "version": "2.2.2",
      "requirements": []
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "alarmo": {
      "version": "v1.9.14",
      "requirements": []
    },
    "satellitetracker": {
      "version": "0.0.8",
      "requirements": [
        "n2yoasync==0.0.6"
      ]
    },
    "anniversaries": {
      "version": "5.2.0",
      "requirements": [
        "python-dateutil>=2.8.1",
        "integrationhelper>=0.2.2",
        "voluptuous>=0.12.1"
      ]
    },
    "spook": {
      "version": "2.2.2",
      "requirements": []
    },
    "solaredgeoptimizers": {
      "version": "1.2.2",
      "requirements": [
        "solaredgeoptimizers==1.0.12",
        "jsonfinder==0.4.2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "codeowners": [
      "@bottlecapdave"
    ],
    "config_flow": true,
    "dependencies": [
      "repairs",
      "recorder"
    ],
    "documentation": "https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy",
    "homekit": {},
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "version": "10.1.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "id": "A-E0D4DE23",
    "octoplus_enrolled": true,
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "106C - EDMI Metering Europe",
            "model": "10E2A100",
            "firmware": "0314B700"
          }
        ],
        "agreements": [
          {
            "start": "2024-02-15T00:00:00+00:00",
            "end": "2025-02-15T00:00:00+00:00",
            "tariff_code": "E-1R-AGILE-23-12-06-N",
            "product_code": "AGILE-23-12-06"
          }
        ]
      },
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": true,
            "is_smart_meter": true,
            "device_id": null,
            "manufacturer": "106C - EDMI Metering Europe",
            "model": "10E2A100",
            "firmware": "0314B700"
          }
        ],
        "agreements": [
          {
            "start": "2023-09-28T23:00:00+00:00",
            "end": "2024-09-28T23:00:00+00:00",
            "tariff_code": "E-1R-OUTGOING-FIX-12M-19-05-13-N",
            "product_code": "OUTGOING-FIX-12M-19-05-13"
          }
        ]
      }
    ],
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "consumption_units": "m\u00b3",
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "106C - EDMI Metering Europe",
            "model": "10F2A100",
            "firmware": "0309BB00"
          }
        ],
        "agreements": [
          {
            "start": "2024-02-15T00:00:00+00:00",
            "end": "2025-02-15T00:00:00+00:00",
            "tariff_code": "G-1R-SILVER-23-12-06-N",
            "product_code": "SILVER-23-12-06"
          }
        ]
      }
    ]
  }
}
```

There's nothing relevant in the HA logs. 

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment]
Sorry you're seeing this.

Do you have any errors in your logs?
Have you tried restarting your HA instance or reloading the integration since?

The fact the last evaluated timestamp is quite old (this should be updated roughly every minute) means that HA hasn't fired the event that the entity is listening for, so is probably out of my control I'm afraid.

**Comment by Daverover66** [comment]
Not seeing any errors in the logs.  I've changed the setting of that target rate sensor to this

```
name: intermittent_best_rates_3_hours_overnight
hours: "3.0"
type: Intermittent
mpan: "2400000260098"
rolling_target: true
last_rates: true
target_invert_target_rates: false
start_time: "10:30"
end_time: "16:00"
kind: target_rate
account_id: A-E0D4DE23
is_target_export: false
rates_incomplete: false
target_times:
  - value_inc_vat: 0.12348
    start: "2024-02-17T12:00:00+00:00"
    end: "2024-02-17T12:30:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.12285
    start: "2024-02-17T12:30:00+00:00"
    end: "2024-02-17T13:00:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.12285
    start: "2024-02-17T13:00:00+00:00"
    end: "2024-02-17T13:30:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.11991
    start: "2024-02-17T13:30:00+00:00"
    end: "2024-02-17T14:00:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.12285
    start: "2024-02-17T14:30:00+00:00"
    end: "2024-02-17T15:00:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
  - value_inc_vat: 0.12348
    start: "2024-02-17T15:30:00+00:00"
    end: "2024-02-17T16:00:00+00:00"
    tariff_code: E-1R-AGILE-23-12-06-N
    is_capped: false
target_times_last_evaluated: "2024-02-17T10:03:02.521043+00:00"
overall_average_cost: 0.12257
overall_min_cost: 0.11991
overall_max_cost: 0.12348
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: "2024-02-17T12:00:00+00:00"
next_duration_in_hours: 2
next_average_cost: 0.1222725
next_min_cost: 0.11991
next_max_cost: 0.12348
last_evaluated: "2024-02-17T10:20:02.520049+00:00"
icon: mdi:camera-timer
friendly_name: Octopus Energy Target intermittent_best_rates_3_hours_overnight
```
It re-evaluated after I submitted the new times and gave me some target rates, which show up on my rate card

![Target Rates](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/109820608/7dff6b7d-44fd-4a8e-b6a2-12975b5d1984)

I'll let you know what happens at midday.

If it doesn't turn on I'll restart HA and try again.
