### ISSUE TITLE
Export tracker issue

### ISSUE THREAD

**Issue by alfwro13** [BottlecapDave/HomeAssistant-OctopusEnergy#901]
### Describe the bug

I woke up this morning and have noticed that overnight I somehow exported nearly £800 worth of energy according to the energy tracker provided by this integration:

```
state_class: total
last_reset: 2024-04-08T00:00:00+01:00
name: export
mpan: 1900092354229
target_entity_id: sensor.shellyem_channel_1_energy_returned
entity_accumulative_value: true
weekday_reset: 0
month_day_reset: 1
kind: cost_tracker
is_tracking: true
tracked_charges: 
- start: '2024-06-08T00:00:00+01:00'
  end: '2024-06-08T00:30:00+01:00'
  rate: 0.15
  consumption: 0.007700000000113505
  cost: 0.0011550000000170257
- start: '2024-06-08T00:30:00+01:00'
  end: '2024-06-08T01:00:00+01:00'
  rate: 0.15
  consumption: 0.00029999999992469384
  cost: 0.00004499999998870407
- start: '2024-06-08T01:00:00+01:00'
  end: '2024-06-08T01:30:00+01:00'
  rate: 0.15
  **consumption: 1764.6992
  cost: 264.70488**
- start: '2024-06-08T01:30:00+01:00'
  end: '2024-06-08T02:00:00+01:00'
  rate: 0.15
  consumption: 0.00009999999997489795
  cost: 0.000014999999996234692
- start: '2024-06-08T02:00:00+01:00'
  end: '2024-06-08T02:30:00+01:00'
  rate: 0.15
  consumption: 0.0018000000000029104
  cost: 0.00027000000000043656
- start: '2024-06-08T02:30:00+01:00'
  end: '2024-06-08T03:00:00+01:00'
  rate: 0.15
  **consumption: 1764.7014
  cost: 264.70521**
- start: '2024-06-08T04:00:00+01:00'
  end: '2024-06-08T04:30:00+01:00'
  rate: 0.15
  consumption: 0.00009999999997489795
  cost: 0.000014999999996234692
- start: '2024-06-08T04:30:00+01:00'
  end: '2024-06-08T05:00:00+01:00'
  rate: 0.15
  **consumption: 1764.7023
  cost: 264.70534499999997**
- start: '2024-06-08T05:00:00+01:00'
  end: '2024-06-08T05:30:00+01:00'
  rate: 0.15
  consumption: 0.00009999999997489795
  cost: 0.000014999999996234692
- start: '2024-06-08T06:00:00+01:00'
  end: '2024-06-08T06:30:00+01:00'
  rate: 0.15
  consumption: 1.0064000000002125
  cost: 0.15096000000003187
- start: '2024-06-08T06:30:00+01:00'
  end: '2024-06-08T07:00:00+01:00'
  rate: 0.15
  consumption: 0.08599999999978536
  cost: 0.012899999999967804

untracked_charges: 
total_consumption: 5295.205400000001
unit_of_measurement: GBP
device_class: monetary
icon: mdi:currency-gbp
friendly_name: Octopus Energy Cost Tracker export
```

I also have a [energy meter](https://github.com/zeronounours/HA-custom-component-energy-meter) using the very same entity (sensor.shellyem_channel_1_energy_returned) and that is reporting the correct amount so I know the issue is not with data reported by that entity.

### Reproduction steps

Setup export tracker and let it run

### Expected behaviour

It should accurately track energy usage - same way utility meter does

### Tariff Code

E-1R-AGILE-23-12-06-J

### Integration Version

11.0.2

### Home Assistant Version

2024.6.0

### Fresh Install?

After upgrading

### Home Assistant Logs

debug logging was not enabled at the time this has happened - it is running now so when that occurs I'll update

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)
